# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_communication(object):
    def setupUi(self, communication):
        communication.setObjectName("communication")
        communication.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(communication.sizePolicy().hasHeightForWidth())
        communication.setSizePolicy(sizePolicy)
        communication.setMinimumSize(QtCore.QSize(400, 300))
        communication.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Robot.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        communication.setWindowIcon(icon)
        communication.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)

        self.frame2 = QtWidgets.QFrame(communication)
        self.frame2.setGeometry(QtCore.QRect(0, 0, 401, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame2.sizePolicy().hasHeightForWidth())
        self.frame2.setSizePolicy(sizePolicy)
        self.frame2.setStyleSheet("background-color: rgb(179, 182, 183);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.frame2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setLineWidth(2)
        self.frame2.setMidLineWidth(0)
        self.frame2.setObjectName("frame2")
        self.comboBox_comPort = QtWidgets.QComboBox(self.frame2)
        self.comboBox_comPort.setGeometry(QtCore.QRect(20, 160, 141, 41))
        self.comboBox_comPort.setStyleSheet("QComboBox{font: 75 16pt \"Arial\";\n"
"background-color: rgb(159, 159, 159);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px\n"
"}\n"
"QComboBox:hover {\n"
"    border: 3px solid rgb(77, 77, 77);\n"
"    color: rgb(77, 77, 77);\n"
"}")
        self.comboBox_comPort.setObjectName("comboBox_comPort")
        self.pushButton = QtWidgets.QPushButton(self.frame2)
        self.pushButton.setGeometry(QtCore.QRect(180, 240, 93, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setMouseTracking(False)
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton { background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(77, 77, 77);\n"
"    color: rgb(77, 77, 77);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame2)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 240, 93, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(77, 77, 77);\n"
"    color: rgb(77, 77, 77);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_39 = QtWidgets.QLabel(self.frame2)
        self.label_39.setGeometry(QtCore.QRect(20, 10, 351, 51))
        self.label_39.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_39.setObjectName("label_39")
        self.comboBox_baudRate = QtWidgets.QComboBox(self.frame2)
        self.comboBox_baudRate.setGeometry(QtCore.QRect(230, 160, 141, 41))
        self.comboBox_baudRate.setStyleSheet("QComboBox{font: 75 16pt \"Arial\";\n"
"background-color: rgb(159, 159, 159);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px\n"
"}\n"
"QComboBox:hover {\n"
"    border: 3px solid rgb(77, 77, 77);\n"
"    color: rgb(77, 77, 77);\n"
"}")
        self.comboBox_baudRate.setObjectName("comboBox_baudRate")
        self.label_40 = QtWidgets.QLabel(self.frame2)
        self.label_40.setGeometry(QtCore.QRect(230, 100, 141, 51))
        self.label_40.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame2)
        self.label_41.setGeometry(QtCore.QRect(20, 100, 141, 51))
        self.label_41.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_41.setObjectName("label_41")
        self.pushButton_2.raise_()
        self.comboBox_comPort.raise_()
        self.pushButton.raise_()
        self.label_39.raise_()
        self.comboBox_baudRate.raise_()
        self.label_40.raise_()
        self.label_41.raise_()

        self.retranslateUi(communication)
        QtCore.QMetaObject.connectSlotsByName(communication)

    def retranslateUi(self, communication):
        _translate = QtCore.QCoreApplication.translate
        communication.setWindowTitle(_translate("communication", "Communication"))
        self.pushButton.setText(_translate("communication", "OK"))
        self.pushButton_2.setText(_translate("communication", "RESET"))
        self.label_39.setText(_translate("communication", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">COMMUNICATION</span></p></body></html>"))
        self.label_40.setText(_translate("communication", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">BAUDRATE</span></p></body></html>"))
        self.label_41.setText(_translate("communication", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">COM PORT</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    communication = QtWidgets.QWidget()
    ui = Ui_communication()
    ui.setupUi(communication)
    communication.show()
    sys.exit(app.exec_())
