# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComportWindow(object):
    def setupUi(self, ComportWindow):
        ComportWindow.setObjectName("ComportWindow")
        #ComportWindow.resize(1920, 1080)
        #ComportWindow.setMinimumSize(QtCore.QSize(1920, 1080))
        #ComportWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.frame1 = QtWidgets.QFrame(ComportWindow)
        self.frame1.setGeometry(QtCore.QRect(0, 0, 1080, 161))
        self.frame1.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.frame1.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setLineWidth(2)
        self.frame1.setMidLineWidth(2)
        self.frame1.setObjectName("frame1")
        self.machineName = QtWidgets.QLabel(self.frame1)
        self.machineName.setGeometry(QtCore.QRect(50, 10, 1080, 131))
        self.machineName.setObjectName("machineName")
        self.frame0 = QtWidgets.QFrame(ComportWindow)
        self.frame0.setGeometry(QtCore.QRect(-11, 169, 1080, 591))
        self.frame0.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.frame0.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame0.setLineWidth(2)
        self.frame0.setObjectName("frame0")
        self.frame2 = QtWidgets.QFrame(self.frame0)
        self.frame2.setGeometry(QtCore.QRect(360, 240, 431, 221))
        self.frame2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(223, 223, 223);")
        self.frame2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setLineWidth(2)
        self.frame2.setMidLineWidth(0)
        self.frame2.setObjectName("frame2")
        self.pushButton = QtWidgets.QPushButton(self.frame2)
        self.pushButton.setGeometry(QtCore.QRect(90, 120, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setMouseTracking(False)
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("\n"
"background-color: rgb(200, 196, 190);")
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.frame2)
        self.comboBox.setGeometry(QtCore.QRect(90, 30, 261, 51))
        self.comboBox.setStyleSheet("font: 75 16pt \"Arial\";")
        self.comboBox.setObjectName("comboBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame2)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 120, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame0.raise_()
        self.frame1.raise_()

        self.retranslateUi(ComportWindow)
        QtCore.QMetaObject.connectSlotsByName(ComportWindow)

    def retranslateUi(self, ComportWindow):
        _translate = QtCore.QCoreApplication.translate
        ComportWindow.setWindowTitle(_translate("ComportWindow", "Widget"))
        self.machineName.setText(_translate("ComportWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">KHOI NGUYEN PLASTIC.JSC</span></p><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">AUTOMATIC PAINTING MACHINE</span></p></body></html>"))
        self.pushButton.setText(_translate("ComportWindow", "OK"))
        self.pushButton_2.setText(_translate("ComportWindow", "RESET"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ComportWindow = QtWidgets.QWidget()
    ui = Ui_ComportWindow()
    ui.setupUi(ComportWindow)
    ComportWindow.show()
    sys.exit(app.exec_())
