# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'defineXYWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_definePinsXY(object):
    def setupUi(self, definePinsXY):
        definePinsXY.setObjectName("definePinsXY")
        definePinsXY.resize(952, 801)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Robot.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        definePinsXY.setWindowIcon(icon)
        definePinsXY.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        self.frame_definePins = QtWidgets.QFrame(definePinsXY)
        self.frame_definePins.setGeometry(QtCore.QRect(0, 0, 951, 801))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_definePins.sizePolicy().hasHeightForWidth())
        self.frame_definePins.setSizePolicy(sizePolicy)
        self.frame_definePins.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.frame_definePins.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_definePins.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_definePins.setLineWidth(2)
        self.frame_definePins.setMidLineWidth(0)
        self.frame_definePins.setObjectName("frame_definePins")
        self.pushButton_Save = QtWidgets.QPushButton(self.frame_definePins)
        self.pushButton_Save.setGeometry(QtCore.QRect(840, 750, 93, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setMouseTracking(False)
        self.pushButton_Save.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_Save.setAutoFillBackground(False)
        self.pushButton_Save.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.label_Pins_01 = QtWidgets.QLabel(self.frame_definePins)
        self.label_Pins_01.setGeometry(QtCore.QRect(20, 10, 871, 51))
        self.label_Pins_01.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Pins_01.setObjectName("label_Pins_01")
        self.label_Pins_02 = QtWidgets.QLabel(self.frame_definePins)
        self.label_Pins_02.setGeometry(QtCore.QRect(20, 80, 221, 51))
        self.label_Pins_02.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Pins_02.setObjectName("label_Pins_02")
        self.label_Pins_3 = QtWidgets.QLabel(self.frame_definePins)
        self.label_Pins_3.setGeometry(QtCore.QRect(290, 80, 201, 51))
        self.label_Pins_3.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Pins_3.setObjectName("label_Pins_3")
        self.label_x1 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x1.setGeometry(QtCore.QRect(30, 140, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x1.setFont(font)
        self.label_x1.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x1.setObjectName("label_x1")
        self.label_x2 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x2.setGeometry(QtCore.QRect(30, 180, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x2.setFont(font)
        self.label_x2.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x2.setObjectName("label_x2")
        self.label_x3 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x3.setGeometry(QtCore.QRect(30, 220, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x3.setFont(font)
        self.label_x3.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x3.setObjectName("label_x3")
        self.label_x4 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x4.setGeometry(QtCore.QRect(30, 260, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x4.setFont(font)
        self.label_x4.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x4.setObjectName("label_x4")
        self.label_x5 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x5.setGeometry(QtCore.QRect(30, 300, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x5.setFont(font)
        self.label_x5.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x5.setObjectName("label_x5")
        self.label_x6 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x6.setGeometry(QtCore.QRect(30, 340, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x6.setFont(font)
        self.label_x6.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x6.setObjectName("label_x6")
        self.label_x7 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x7.setGeometry(QtCore.QRect(30, 380, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x7.setFont(font)
        self.label_x7.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x7.setObjectName("label_x7")
        self.label_x8 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x8.setGeometry(QtCore.QRect(30, 420, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x8.setFont(font)
        self.label_x8.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x8.setObjectName("label_x8")
        self.label_x9 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x9.setGeometry(QtCore.QRect(30, 460, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x9.setFont(font)
        self.label_x9.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x9.setObjectName("label_x9")
        self.label_x10 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x10.setGeometry(QtCore.QRect(30, 500, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x10.setFont(font)
        self.label_x10.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x10.setObjectName("label_x10")
        self.label_x11 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x11.setGeometry(QtCore.QRect(30, 540, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x11.setFont(font)
        self.label_x11.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x11.setObjectName("label_x11")
        self.label_x12 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x12.setGeometry(QtCore.QRect(30, 580, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x12.setFont(font)
        self.label_x12.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x12.setObjectName("label_x12")
        self.label_x13 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x13.setGeometry(QtCore.QRect(30, 620, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x13.setFont(font)
        self.label_x13.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x13.setObjectName("label_x13")
        self.label_x14 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x14.setGeometry(QtCore.QRect(30, 660, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x14.setFont(font)
        self.label_x14.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x14.setObjectName("label_x14")
        self.label_x15 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x15.setGeometry(QtCore.QRect(30, 700, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x15.setFont(font)
        self.label_x15.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x15.setObjectName("label_x15")
        self.label_x16 = QtWidgets.QLabel(self.frame_definePins)
        self.label_x16.setGeometry(QtCore.QRect(30, 740, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x16.setFont(font)
        self.label_x16.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x16.setObjectName("label_x16")
        self.label_y10 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y10.setGeometry(QtCore.QRect(300, 500, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y10.setFont(font)
        self.label_y10.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y10.setObjectName("label_y10")
        self.label_y13 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y13.setGeometry(QtCore.QRect(300, 620, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y13.setFont(font)
        self.label_y13.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y13.setObjectName("label_y13")
        self.label_y3 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y3.setGeometry(QtCore.QRect(300, 220, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y3.setFont(font)
        self.label_y3.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y3.setObjectName("label_y3")
        self.label_y5 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y5.setGeometry(QtCore.QRect(300, 300, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y5.setFont(font)
        self.label_y5.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y5.setObjectName("label_y5")
        self.label_y2 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y2.setGeometry(QtCore.QRect(300, 180, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y2.setFont(font)
        self.label_y2.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y2.setObjectName("label_y2")
        self.label_y14 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y14.setGeometry(QtCore.QRect(300, 660, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y14.setFont(font)
        self.label_y14.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y14.setObjectName("label_y14")
        self.label_y8 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y8.setGeometry(QtCore.QRect(300, 420, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y8.setFont(font)
        self.label_y8.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y8.setObjectName("label_y8")
        self.label_y6 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y6.setGeometry(QtCore.QRect(300, 340, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y6.setFont(font)
        self.label_y6.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y6.setObjectName("label_y6")
        self.label_y7 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y7.setGeometry(QtCore.QRect(300, 380, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y7.setFont(font)
        self.label_y7.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y7.setObjectName("label_y7")
        self.label_y16 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y16.setGeometry(QtCore.QRect(300, 740, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y16.setFont(font)
        self.label_y16.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y16.setObjectName("label_y16")
        self.label_y1 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y1.setGeometry(QtCore.QRect(300, 140, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y1.setFont(font)
        self.label_y1.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y1.setObjectName("label_y1")
        self.label_y12 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y12.setGeometry(QtCore.QRect(300, 580, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y12.setFont(font)
        self.label_y12.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y12.setObjectName("label_y12")
        self.label_y11 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y11.setGeometry(QtCore.QRect(300, 540, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y11.setFont(font)
        self.label_y11.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y11.setObjectName("label_y11")
        self.label_y15 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y15.setGeometry(QtCore.QRect(300, 700, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y15.setFont(font)
        self.label_y15.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y15.setObjectName("label_y15")
        self.label_y4 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y4.setGeometry(QtCore.QRect(300, 260, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y4.setFont(font)
        self.label_y4.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y4.setObjectName("label_y4")
        self.label_y9 = QtWidgets.QLabel(self.frame_definePins)
        self.label_y9.setGeometry(QtCore.QRect(300, 460, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y9.setFont(font)
        self.label_y9.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y9.setObjectName("label_y9")
        self.spinBox_X1 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X1.setGeometry(QtCore.QRect(160, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X1.setFont(font)
        self.spinBox_X1.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X1.setMaximum(15)
        self.spinBox_X1.setObjectName("spinBox_X1")
        self.spinBox_X2 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X2.setGeometry(QtCore.QRect(160, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X2.setFont(font)
        self.spinBox_X2.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X2.setMaximum(15)
        self.spinBox_X2.setObjectName("spinBox_X2")
        self.spinBox_X3 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X3.setGeometry(QtCore.QRect(160, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X3.setFont(font)
        self.spinBox_X3.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X3.setMaximum(15)
        self.spinBox_X3.setObjectName("spinBox_X3")
        self.spinBox_X4 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X4.setGeometry(QtCore.QRect(160, 260, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X4.setFont(font)
        self.spinBox_X4.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X4.setMaximum(15)
        self.spinBox_X4.setObjectName("spinBox_X4")
        self.spinBox_X5 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X5.setGeometry(QtCore.QRect(160, 300, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X5.setFont(font)
        self.spinBox_X5.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X5.setMaximum(15)
        self.spinBox_X5.setObjectName("spinBox_X5")
        self.spinBox_X6 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X6.setGeometry(QtCore.QRect(160, 340, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X6.setFont(font)
        self.spinBox_X6.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X6.setMaximum(15)
        self.spinBox_X6.setObjectName("spinBox_X6")
        self.spinBox_X7 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X7.setGeometry(QtCore.QRect(160, 380, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X7.setFont(font)
        self.spinBox_X7.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X7.setMaximum(15)
        self.spinBox_X7.setObjectName("spinBox_X7")
        self.spinBox_X8 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X8.setGeometry(QtCore.QRect(160, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X8.setFont(font)
        self.spinBox_X8.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X8.setMaximum(15)
        self.spinBox_X8.setObjectName("spinBox_X8")
        self.spinBox_X9 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X9.setGeometry(QtCore.QRect(160, 460, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X9.setFont(font)
        self.spinBox_X9.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X9.setMaximum(15)
        self.spinBox_X9.setObjectName("spinBox_X9")
        self.spinBox_X10 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X10.setGeometry(QtCore.QRect(160, 500, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X10.setFont(font)
        self.spinBox_X10.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X10.setMaximum(15)
        self.spinBox_X10.setObjectName("spinBox_X10")
        self.spinBox_X11 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X11.setGeometry(QtCore.QRect(160, 540, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X11.setFont(font)
        self.spinBox_X11.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X11.setMaximum(15)
        self.spinBox_X11.setObjectName("spinBox_X11")
        self.spinBox_X12 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X12.setGeometry(QtCore.QRect(160, 580, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X12.setFont(font)
        self.spinBox_X12.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X12.setMaximum(15)
        self.spinBox_X12.setObjectName("spinBox_X12")
        self.spinBox_X13 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X13.setGeometry(QtCore.QRect(160, 620, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X13.setFont(font)
        self.spinBox_X13.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X13.setMaximum(15)
        self.spinBox_X13.setObjectName("spinBox_X13")
        self.spinBox_X14 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X14.setGeometry(QtCore.QRect(160, 660, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X14.setFont(font)
        self.spinBox_X14.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X14.setMaximum(15)
        self.spinBox_X14.setObjectName("spinBox_X14")
        self.spinBox_X15 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X15.setGeometry(QtCore.QRect(160, 700, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X15.setFont(font)
        self.spinBox_X15.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X15.setMaximum(15)
        self.spinBox_X15.setObjectName("spinBox_X15")
        self.spinBox_X16 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_X16.setGeometry(QtCore.QRect(160, 740, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_X16.setFont(font)
        self.spinBox_X16.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_X16.setMaximum(15)
        self.spinBox_X16.setObjectName("spinBox_X16")
        self.spinBox_Y5 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y5.setGeometry(QtCore.QRect(410, 300, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y5.setFont(font)
        self.spinBox_Y5.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y5.setMaximum(15)
        self.spinBox_Y5.setObjectName("spinBox_Y5")
        self.spinBox_Y15 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y15.setGeometry(QtCore.QRect(410, 700, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y15.setFont(font)
        self.spinBox_Y15.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y15.setMaximum(15)
        self.spinBox_Y15.setObjectName("spinBox_Y15")
        self.spinBox_Y1 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y1.setGeometry(QtCore.QRect(410, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y1.setFont(font)
        self.spinBox_Y1.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y1.setMaximum(15)
        self.spinBox_Y1.setObjectName("spinBox_Y1")
        self.spinBox_Y6 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y6.setGeometry(QtCore.QRect(410, 340, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y6.setFont(font)
        self.spinBox_Y6.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y6.setMaximum(15)
        self.spinBox_Y6.setObjectName("spinBox_Y6")
        self.spinBox_Y13 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y13.setGeometry(QtCore.QRect(410, 620, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y13.setFont(font)
        self.spinBox_Y13.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y13.setMaximum(15)
        self.spinBox_Y13.setObjectName("spinBox_Y13")
        self.spinBox_Y2 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y2.setGeometry(QtCore.QRect(410, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y2.setFont(font)
        self.spinBox_Y2.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y2.setMaximum(15)
        self.spinBox_Y2.setObjectName("spinBox_Y2")
        self.spinBox_Y8 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y8.setGeometry(QtCore.QRect(410, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y8.setFont(font)
        self.spinBox_Y8.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y8.setMaximum(15)
        self.spinBox_Y8.setObjectName("spinBox_Y8")
        self.spinBox_Y11 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y11.setGeometry(QtCore.QRect(410, 540, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y11.setFont(font)
        self.spinBox_Y11.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y11.setMaximum(15)
        self.spinBox_Y11.setObjectName("spinBox_Y11")
        self.spinBox_Y12 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y12.setGeometry(QtCore.QRect(410, 580, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y12.setFont(font)
        self.spinBox_Y12.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y12.setMaximum(15)
        self.spinBox_Y12.setObjectName("spinBox_Y12")
        self.spinBox_Y14 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y14.setGeometry(QtCore.QRect(410, 660, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y14.setFont(font)
        self.spinBox_Y14.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y14.setMaximum(15)
        self.spinBox_Y14.setObjectName("spinBox_Y14")
        self.spinBox_Y9 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y9.setGeometry(QtCore.QRect(410, 460, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y9.setFont(font)
        self.spinBox_Y9.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y9.setMaximum(15)
        self.spinBox_Y9.setObjectName("spinBox_Y9")
        self.spinBox_Y4 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y4.setGeometry(QtCore.QRect(410, 260, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y4.setFont(font)
        self.spinBox_Y4.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y4.setMaximum(15)
        self.spinBox_Y4.setObjectName("spinBox_Y4")
        self.spinBox_Y7 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y7.setGeometry(QtCore.QRect(410, 380, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y7.setFont(font)
        self.spinBox_Y7.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y7.setMaximum(15)
        self.spinBox_Y7.setObjectName("spinBox_Y7")
        self.spinBox_Y16 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y16.setGeometry(QtCore.QRect(410, 740, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y16.setFont(font)
        self.spinBox_Y16.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y16.setMaximum(15)
        self.spinBox_Y16.setObjectName("spinBox_Y16")
        self.spinBox_Y10 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y10.setGeometry(QtCore.QRect(410, 500, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y10.setFont(font)
        self.spinBox_Y10.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y10.setMaximum(15)
        self.spinBox_Y10.setObjectName("spinBox_Y10")
        self.spinBox_Y3 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_Y3.setGeometry(QtCore.QRect(410, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_Y3.setFont(font)
        self.spinBox_Y3.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_Y3.setMaximum(15)
        self.spinBox_Y3.setObjectName("spinBox_Y3")
        self.pushButton_Edit = QtWidgets.QPushButton(self.frame_definePins)
        self.pushButton_Edit.setGeometry(QtCore.QRect(840, 690, 93, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Edit.setFont(font)
        self.pushButton_Edit.setMouseTracking(False)
        self.pushButton_Edit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_Edit.setAutoFillBackground(False)
        self.pushButton_Edit.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.pushButton_Edit.setObjectName("pushButton_Edit")
        self.label_xhome = QtWidgets.QLabel(self.frame_definePins)
        self.label_xhome.setGeometry(QtCore.QRect(540, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_xhome.setFont(font)
        self.label_xhome.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_xhome.setObjectName("label_xhome")
        self.label_yhome = QtWidgets.QLabel(self.frame_definePins)
        self.label_yhome.setGeometry(QtCore.QRect(540, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_yhome.setFont(font)
        self.label_yhome.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_yhome.setObjectName("label_yhome")
        self.label_zhome = QtWidgets.QLabel(self.frame_definePins)
        self.label_zhome.setGeometry(QtCore.QRect(540, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_zhome.setFont(font)
        self.label_zhome.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_zhome.setObjectName("label_zhome")
        self.label_ahome = QtWidgets.QLabel(self.frame_definePins)
        self.label_ahome.setGeometry(QtCore.QRect(540, 260, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_ahome.setFont(font)
        self.label_ahome.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_ahome.setObjectName("label_ahome")
        self.label_xlimit = QtWidgets.QLabel(self.frame_definePins)
        self.label_xlimit.setGeometry(QtCore.QRect(740, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_xlimit.setFont(font)
        self.label_xlimit.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_xlimit.setObjectName("label_xlimit")
        self.label_alimit = QtWidgets.QLabel(self.frame_definePins)
        self.label_alimit.setGeometry(QtCore.QRect(740, 260, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_alimit.setFont(font)
        self.label_alimit.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_alimit.setObjectName("label_alimit")
        self.label_zlimit = QtWidgets.QLabel(self.frame_definePins)
        self.label_zlimit.setGeometry(QtCore.QRect(740, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_zlimit.setFont(font)
        self.label_zlimit.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_zlimit.setObjectName("label_zlimit")
        self.label_ylimit = QtWidgets.QLabel(self.frame_definePins)
        self.label_ylimit.setGeometry(QtCore.QRect(740, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_ylimit.setFont(font)
        self.label_ylimit.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_ylimit.setObjectName("label_ylimit")
        self.spinBox_xhome = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_xhome.setGeometry(QtCore.QRect(650, 140, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_xhome.setFont(font)
        self.spinBox_xhome.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_xhome.setMinimum(1)
        self.spinBox_xhome.setMaximum(16)
        self.spinBox_xhome.setObjectName("spinBox_xhome")
        self.spinBox_yhome = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_yhome.setGeometry(QtCore.QRect(650, 180, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_yhome.setFont(font)
        self.spinBox_yhome.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_yhome.setMinimum(1)
        self.spinBox_yhome.setMaximum(16)
        self.spinBox_yhome.setObjectName("spinBox_yhome")
        self.spinBox_zhome = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_zhome.setGeometry(QtCore.QRect(650, 220, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_zhome.setFont(font)
        self.spinBox_zhome.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_zhome.setMinimum(1)
        self.spinBox_zhome.setMaximum(16)
        self.spinBox_zhome.setObjectName("spinBox_zhome")
        self.spinBox_ahome = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_ahome.setGeometry(QtCore.QRect(650, 260, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_ahome.setFont(font)
        self.spinBox_ahome.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_ahome.setMinimum(1)
        self.spinBox_ahome.setMaximum(16)
        self.spinBox_ahome.setObjectName("spinBox_ahome")
        self.spinBox_zlimit = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_zlimit.setGeometry(QtCore.QRect(850, 220, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_zlimit.setFont(font)
        self.spinBox_zlimit.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_zlimit.setMinimum(1)
        self.spinBox_zlimit.setMaximum(16)
        self.spinBox_zlimit.setObjectName("spinBox_zlimit")
        self.spinBox_alimit = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_alimit.setGeometry(QtCore.QRect(850, 260, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_alimit.setFont(font)
        self.spinBox_alimit.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_alimit.setMinimum(1)
        self.spinBox_alimit.setMaximum(16)
        self.spinBox_alimit.setObjectName("spinBox_alimit")
        self.spinBox_xlimit = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_xlimit.setGeometry(QtCore.QRect(850, 140, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_xlimit.setFont(font)
        self.spinBox_xlimit.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_xlimit.setMinimum(1)
        self.spinBox_xlimit.setMaximum(16)
        self.spinBox_xlimit.setObjectName("spinBox_xlimit")
        self.spinBox_ylimit = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_ylimit.setGeometry(QtCore.QRect(850, 180, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_ylimit.setFont(font)
        self.spinBox_ylimit.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_ylimit.setMinimum(1)
        self.spinBox_ylimit.setMaximum(16)
        self.spinBox_ylimit.setObjectName("spinBox_ylimit")
        self.label_Pins_4 = QtWidgets.QLabel(self.frame_definePins)
        self.label_Pins_4.setGeometry(QtCore.QRect(540, 80, 371, 51))
        self.label_Pins_4.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Pins_4.setObjectName("label_Pins_4")
        self.label_Pins_5 = QtWidgets.QLabel(self.frame_definePins)
        self.label_Pins_5.setGeometry(QtCore.QRect(540, 320, 371, 51))
        self.label_Pins_5.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Pins_5.setObjectName("label_Pins_5")
        self.spinBox_spray3 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_spray3.setGeometry(QtCore.QRect(750, 460, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_spray3.setFont(font)
        self.spinBox_spray3.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_spray3.setMinimum(1)
        self.spinBox_spray3.setMaximum(16)
        self.spinBox_spray3.setObjectName("spinBox_spray3")
        self.label_spray1 = QtWidgets.QLabel(self.frame_definePins)
        self.label_spray1.setGeometry(QtCore.QRect(540, 380, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_spray1.setFont(font)
        self.label_spray1.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_spray1.setObjectName("label_spray1")
        self.label_spray4 = QtWidgets.QLabel(self.frame_definePins)
        self.label_spray4.setGeometry(QtCore.QRect(540, 500, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_spray4.setFont(font)
        self.label_spray4.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_spray4.setObjectName("label_spray4")
        self.label_rotateTable1 = QtWidgets.QLabel(self.frame_definePins)
        self.label_rotateTable1.setGeometry(QtCore.QRect(540, 540, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_rotateTable1.setFont(font)
        self.label_rotateTable1.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_rotateTable1.setObjectName("label_rotateTable1")
        self.spinBox_spray4 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_spray4.setGeometry(QtCore.QRect(750, 500, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_spray4.setFont(font)
        self.spinBox_spray4.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_spray4.setMinimum(1)
        self.spinBox_spray4.setMaximum(16)
        self.spinBox_spray4.setObjectName("spinBox_spray4")
        self.spinBox_rotateTable2 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_rotateTable2.setGeometry(QtCore.QRect(750, 580, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_rotateTable2.setFont(font)
        self.spinBox_rotateTable2.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_rotateTable2.setMinimum(1)
        self.spinBox_rotateTable2.setMaximum(16)
        self.spinBox_rotateTable2.setObjectName("spinBox_rotateTable2")
        self.label_spray3 = QtWidgets.QLabel(self.frame_definePins)
        self.label_spray3.setGeometry(QtCore.QRect(540, 460, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_spray3.setFont(font)
        self.label_spray3.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_spray3.setObjectName("label_spray3")
        self.spinBox_spray1 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_spray1.setGeometry(QtCore.QRect(750, 380, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_spray1.setFont(font)
        self.spinBox_spray1.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_spray1.setMinimum(1)
        self.spinBox_spray1.setMaximum(16)
        self.spinBox_spray1.setObjectName("spinBox_spray1")
        self.label_rotateTable2 = QtWidgets.QLabel(self.frame_definePins)
        self.label_rotateTable2.setGeometry(QtCore.QRect(540, 580, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_rotateTable2.setFont(font)
        self.label_rotateTable2.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_rotateTable2.setObjectName("label_rotateTable2")
        self.spinBox_spray2 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_spray2.setGeometry(QtCore.QRect(750, 420, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_spray2.setFont(font)
        self.spinBox_spray2.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_spray2.setMinimum(1)
        self.spinBox_spray2.setMaximum(16)
        self.spinBox_spray2.setObjectName("spinBox_spray2")
        self.spinBox_rotateTable1 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_rotateTable1.setGeometry(QtCore.QRect(750, 540, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_rotateTable1.setFont(font)
        self.spinBox_rotateTable1.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_rotateTable1.setMinimum(1)
        self.spinBox_rotateTable1.setMaximum(16)
        self.spinBox_rotateTable1.setObjectName("spinBox_rotateTable1")
        self.label_spray2 = QtWidgets.QLabel(self.frame_definePins)
        self.label_spray2.setGeometry(QtCore.QRect(540, 420, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_spray2.setFont(font)
        self.label_spray2.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_spray2.setObjectName("label_spray2")
        self.label_rotateTable3 = QtWidgets.QLabel(self.frame_definePins)
        self.label_rotateTable3.setGeometry(QtCore.QRect(540, 620, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_rotateTable3.setFont(font)
        self.label_rotateTable3.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_rotateTable3.setObjectName("label_rotateTable3")
        self.spinBox_rotateTable4 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_rotateTable4.setGeometry(QtCore.QRect(750, 660, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_rotateTable4.setFont(font)
        self.spinBox_rotateTable4.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_rotateTable4.setMinimum(1)
        self.spinBox_rotateTable4.setMaximum(16)
        self.spinBox_rotateTable4.setObjectName("spinBox_rotateTable4")
        self.label_rotateTable4 = QtWidgets.QLabel(self.frame_definePins)
        self.label_rotateTable4.setGeometry(QtCore.QRect(540, 660, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_rotateTable4.setFont(font)
        self.label_rotateTable4.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_rotateTable4.setObjectName("label_rotateTable4")
        self.spinBox_rotateTable3 = QtWidgets.QSpinBox(self.frame_definePins)
        self.spinBox_rotateTable3.setGeometry(QtCore.QRect(750, 620, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.spinBox_rotateTable3.setFont(font)
        self.spinBox_rotateTable3.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.spinBox_rotateTable3.setMinimum(1)
        self.spinBox_rotateTable3.setMaximum(16)
        self.spinBox_rotateTable3.setObjectName("spinBox_rotateTable3")

        self.retranslateUi(definePinsXY)
        QtCore.QMetaObject.connectSlotsByName(definePinsXY)

    def retranslateUi(self, definePinsXY):
        _translate = QtCore.QCoreApplication.translate
        definePinsXY.setWindowTitle(_translate("definePinsXY", "definePinsXY"))
        self.pushButton_Save.setText(_translate("definePinsXY", "SAVE"))
        self.label_Pins_01.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">DEFINE X/Y PINS </span></p></body></html>"))
        self.label_Pins_02.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X SINALS - PIN</span></p></body></html>"))
        self.label_Pins_3.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y SINALS - PIN</span></p></body></html>"))
        self.label_x1.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X1</span></p></body></html>"))
        self.label_x2.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X2</span></p></body></html>"))
        self.label_x3.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X3</span></p></body></html>"))
        self.label_x4.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X4</span></p></body></html>"))
        self.label_x5.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X5</span></p></body></html>"))
        self.label_x6.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X6</span></p></body></html>"))
        self.label_x7.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X7</span></p></body></html>"))
        self.label_x8.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X8</span></p></body></html>"))
        self.label_x9.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X9</span></p></body></html>"))
        self.label_x10.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X10</span></p></body></html>"))
        self.label_x11.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X11</span></p></body></html>"))
        self.label_x12.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X12</span></p></body></html>"))
        self.label_x13.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X13</span></p></body></html>"))
        self.label_x14.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X14</span></p></body></html>"))
        self.label_x15.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X15</span></p></body></html>"))
        self.label_x16.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X16</span></p></body></html>"))
        self.label_y10.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y10</span></p></body></html>"))
        self.label_y13.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y13</span></p></body></html>"))
        self.label_y3.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y3</span></p></body></html>"))
        self.label_y5.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y5</span></p></body></html>"))
        self.label_y2.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y2</span></p></body></html>"))
        self.label_y14.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y14</span></p></body></html>"))
        self.label_y8.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y8</span></p></body></html>"))
        self.label_y6.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y6</span></p></body></html>"))
        self.label_y7.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y7</span></p></body></html>"))
        self.label_y16.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y16</span></p></body></html>"))
        self.label_y1.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y1</span></p></body></html>"))
        self.label_y12.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y12</span></p></body></html>"))
        self.label_y11.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y11</span></p></body></html>"))
        self.label_y15.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y15</span></p></body></html>"))
        self.label_y4.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y4</span></p></body></html>"))
        self.label_y9.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y9</span></p></body></html>"))
        self.pushButton_Edit.setText(_translate("definePinsXY", "EDIT"))
        self.label_xhome.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">XHOME</span></p></body></html>"))
        self.label_yhome.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">YHOME</span></p></body></html>"))
        self.label_zhome.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">ZHOME</span></p></body></html>"))
        self.label_ahome.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">AHOME</span></p></body></html>"))
        self.label_xlimit.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">XLIMIT</span></p></body></html>"))
        self.label_alimit.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">ALIMIT</span></p></body></html>"))
        self.label_zlimit.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">ZLIMIT</span></p></body></html>"))
        self.label_ylimit.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">YLIMIT</span></p></body></html>"))
        self.label_Pins_4.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X SIGNAL DEFINE</span></p></body></html>"))
        self.label_Pins_5.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y SIGNAL DEFINE</span></p></body></html>"))
        self.label_spray1.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">SPRAY1</span></p></body></html>"))
        self.label_spray4.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">SPRAY4</span></p></body></html>"))
        self.label_rotateTable1.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">ROTATE TABLE 1</span></p></body></html>"))
        self.label_spray3.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">SPRAY3</span></p></body></html>"))
        self.label_rotateTable2.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">ROTATE TABLE 2</span></p></body></html>"))
        self.label_spray2.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">SPRAY2</span></p></body></html>"))
        self.label_rotateTable3.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">ROTATE TABLE 3</span></p></body></html>"))
        self.label_rotateTable4.setText(_translate("definePinsXY", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">ROTATE TABLE 4</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    definePinsXY = QtWidgets.QWidget()
    ui = Ui_definePinsXY()
    ui.setupUi(definePinsXY)
    definePinsXY.show()
    sys.exit(app.exec_())
