# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setMotor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_paramWindow(object):
    def setupUi(self, paramWindow):
        paramWindow.setObjectName("paramWindow")
        paramWindow.resize(1031, 474)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Robot.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        paramWindow.setWindowIcon(icon)
        self.setting_frame = QtWidgets.QFrame(paramWindow)
        self.setting_frame.setGeometry(QtCore.QRect(0, 0, 1031, 471))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting_frame.sizePolicy().hasHeightForWidth())
        self.setting_frame.setSizePolicy(sizePolicy)
        self.setting_frame.setStyleSheet("\n"
"background-color: rgb(223, 223, 223);")
        self.setting_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.setting_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setting_frame.setLineWidth(2)
        self.setting_frame.setMidLineWidth(0)
        self.setting_frame.setObjectName("setting_frame")
        self.label_39 = QtWidgets.QLabel(self.setting_frame)
        self.label_39.setGeometry(QtCore.QRect(10, 20, 851, 41))
        self.label_39.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_39.setObjectName("label_39")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.setting_frame)
        self.buttonBox.setGeometry(QtCore.QRect(820, 410, 193, 50))
        self.buttonBox.setStyleSheet("background-color: rgb(200, 196, 190);\n"
"")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.line = QtWidgets.QFrame(self.setting_frame)
        self.line.setGeometry(QtCore.QRect(20, 80, 991, 311))
        self.line.setStyleSheet("border: 3px solid  rgb(56, 56, 56);\n"
"border-radius: 2px")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.setting_frame)
        self.line_2.setGeometry(QtCore.QRect(30, 130, 971, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.setting_frame)
        self.line_3.setGeometry(QtCore.QRect(30, 190, 971, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.setting_frame)
        self.line_4.setGeometry(QtCore.QRect(30, 260, 971, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.setting_frame)
        self.line_5.setGeometry(QtCore.QRect(30, 330, 971, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.setting_frame)
        self.line_6.setEnabled(True)
        self.line_6.setGeometry(QtCore.QRect(300, 90, 20, 291))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.setting_frame)
        self.line_7.setEnabled(True)
        self.line_7.setGeometry(QtCore.QRect(450, 90, 20, 291))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.setting_frame)
        self.line_8.setEnabled(True)
        self.line_8.setGeometry(QtCore.QRect(590, 90, 20, 291))
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.setting_frame)
        self.line_9.setEnabled(True)
        self.line_9.setGeometry(QtCore.QRect(730, 90, 20, 291))
        self.line_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.setting_frame)
        self.line_10.setEnabled(True)
        self.line_10.setGeometry(QtCore.QRect(870, 90, 20, 291))
        self.line_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.setting_frame)
        self.line_11.setEnabled(True)
        self.line_11.setGeometry(QtCore.QRect(150, 90, 20, 291))
        self.line_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setObjectName("line_11")
        self.lineEdit = QtWidgets.QLineEdit(self.setting_frame)
        self.lineEdit.setGeometry(QtCore.QRect(30, 91, 121, 41))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(paramWindow)
        QtCore.QMetaObject.connectSlotsByName(paramWindow)

    def retranslateUi(self, paramWindow):
        _translate = QtCore.QCoreApplication.translate
        paramWindow.setWindowTitle(_translate("paramWindow", "ParameterSettings"))
        self.label_39.setText(_translate("paramWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">MOTOR SETTINGS</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    paramWindow = QtWidgets.QWidget()
    ui = Ui_paramWindow()
    ui.setupUi(paramWindow)
    paramWindow.show()
    sys.exit(app.exec_())
