# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show2DlineWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
import pyqtgraph.opengl as gl


class Ui_plot2D(object):
    def setupUi(self, plot2D):
        plot2D.setObjectName("plot2D")
        plot2D.resize(1018, 810)
        plot2D.setMinimumSize(QtCore.QSize(1018, 810))
        plot2D.setMaximumSize(QtCore.QSize(1018, 810))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Robot.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        plot2D.setWindowIcon(icon)
        plot2D.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        self.graphicsView = PlotWidget(plot2D)
        self.graphicsView.setGeometry(QtCore.QRect(20, 10, 971, 781))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(plot2D)
        QtCore.QMetaObject.connectSlotsByName(plot2D)

    def retranslateUi(self, plot2D):
        _translate = QtCore.QCoreApplication.translate
        plot2D.setWindowTitle(_translate("plot2D", "plot2DWindow"))


