# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teachWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_teachMode(object):
    def setupUi(self, teachMode):
        teachMode.setObjectName("teachMode")
        teachMode.resize(618, 435)
        teachMode.setMinimumSize(QtCore.QSize(618, 435))
        teachMode.setMaximumSize(QtCore.QSize(618, 435))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Robot.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        teachMode.setWindowIcon(icon)
        teachMode.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        self.frame_teachmode = QtWidgets.QFrame(teachMode)
        self.frame_teachmode.setGeometry(QtCore.QRect(10, 0, 601, 431))
        self.frame_teachmode.setStyleSheet("background-color: rgb(179, 182, 183);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.frame_teachmode.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_teachmode.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_teachmode.setObjectName("frame_teachmode")
        self.label_39 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_39.setGeometry(QtCore.QRect(10, 10, 581, 51))
        self.label_39.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_40.setGeometry(QtCore.QRect(10, 70, 61, 51))
        self.label_40.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_41.setGeometry(QtCore.QRect(10, 130, 61, 51))
        self.label_41.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_42.setGeometry(QtCore.QRect(10, 190, 61, 51))
        self.label_42.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_43.setGeometry(QtCore.QRect(10, 250, 61, 51))
        self.label_43.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_44.setGeometry(QtCore.QRect(10, 310, 61, 51))
        self.label_44.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_45.setGeometry(QtCore.QRect(10, 370, 61, 51))
        self.label_45.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_45.setObjectName("label_45")
        self.pushButton_xFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_xFw.setGeometry(QtCore.QRect(80, 70, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_xFw.setFont(font)
        self.pushButton_xFw.setMouseTracking(True)
        self.pushButton_xFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_xFw.setAutoFillBackground(False)
        self.pushButton_xFw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_xFw.setFlat(False)
        self.pushButton_xFw.setObjectName("pushButton_xFw")
        self.pushButton_xRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_xRw.setGeometry(QtCore.QRect(200, 70, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_xRw.setFont(font)
        self.pushButton_xRw.setMouseTracking(False)
        self.pushButton_xRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_xRw.setAutoFillBackground(False)
        self.pushButton_xRw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_xRw.setFlat(False)
        self.pushButton_xRw.setObjectName("pushButton_xRw")
        self.pushButton_yFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_yFw.setGeometry(QtCore.QRect(80, 130, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_yFw.setFont(font)
        self.pushButton_yFw.setMouseTracking(False)
        self.pushButton_yFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_yFw.setAutoFillBackground(False)
        self.pushButton_yFw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_yFw.setFlat(False)
        self.pushButton_yFw.setObjectName("pushButton_yFw")
        self.pushButton_zFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_zFw.setGeometry(QtCore.QRect(80, 190, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_zFw.setFont(font)
        self.pushButton_zFw.setMouseTracking(False)
        self.pushButton_zFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_zFw.setAutoFillBackground(False)
        self.pushButton_zFw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_zFw.setFlat(False)
        self.pushButton_zFw.setObjectName("pushButton_zFw")
        self.pushButton_aFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_aFw.setGeometry(QtCore.QRect(80, 250, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_aFw.setFont(font)
        self.pushButton_aFw.setMouseTracking(False)
        self.pushButton_aFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_aFw.setAutoFillBackground(False)
        self.pushButton_aFw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_aFw.setFlat(False)
        self.pushButton_aFw.setObjectName("pushButton_aFw")
        self.pushButton_bFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_bFw.setGeometry(QtCore.QRect(80, 310, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_bFw.setFont(font)
        self.pushButton_bFw.setMouseTracking(False)
        self.pushButton_bFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_bFw.setAutoFillBackground(False)
        self.pushButton_bFw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_bFw.setFlat(False)
        self.pushButton_bFw.setObjectName("pushButton_bFw")
        self.pushButton_cFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_cFw.setGeometry(QtCore.QRect(80, 370, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_cFw.setFont(font)
        self.pushButton_cFw.setMouseTracking(False)
        self.pushButton_cFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_cFw.setAutoFillBackground(False)
        self.pushButton_cFw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_cFw.setFlat(False)
        self.pushButton_cFw.setObjectName("pushButton_cFw")
        self.pushButton_yRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_yRw.setGeometry(QtCore.QRect(200, 130, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_yRw.setFont(font)
        self.pushButton_yRw.setMouseTracking(False)
        self.pushButton_yRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_yRw.setAutoFillBackground(False)
        self.pushButton_yRw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_yRw.setFlat(False)
        self.pushButton_yRw.setObjectName("pushButton_yRw")
        self.pushButton_zRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_zRw.setGeometry(QtCore.QRect(200, 190, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_zRw.setFont(font)
        self.pushButton_zRw.setMouseTracking(False)
        self.pushButton_zRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_zRw.setAutoFillBackground(False)
        self.pushButton_zRw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_zRw.setFlat(False)
        self.pushButton_zRw.setObjectName("pushButton_zRw")
        self.pushButton_aRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_aRw.setGeometry(QtCore.QRect(200, 250, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_aRw.setFont(font)
        self.pushButton_aRw.setMouseTracking(False)
        self.pushButton_aRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_aRw.setAutoFillBackground(False)
        self.pushButton_aRw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_aRw.setFlat(False)
        self.pushButton_aRw.setObjectName("pushButton_aRw")
        self.pushButton_bRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_bRw.setGeometry(QtCore.QRect(200, 310, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_bRw.setFont(font)
        self.pushButton_bRw.setMouseTracking(False)
        self.pushButton_bRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_bRw.setAutoFillBackground(False)
        self.pushButton_bRw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_bRw.setFlat(False)
        self.pushButton_bRw.setObjectName("pushButton_bRw")
        self.pushButton_cRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_cRw.setGeometry(QtCore.QRect(200, 370, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_cRw.setFont(font)
        self.pushButton_cRw.setMouseTracking(False)
        self.pushButton_cRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_cRw.setAutoFillBackground(False)
        self.pushButton_cRw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_cRw.setFlat(False)
        self.pushButton_cRw.setObjectName("pushButton_cRw")
        self.line = QtWidgets.QFrame(self.frame_teachmode)
        self.line.setGeometry(QtCore.QRect(320, 70, 3, 351))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_z1Up = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_z1Up.setGeometry(QtCore.QRect(344, 310, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_z1Up.setFont(font)
        self.pushButton_z1Up.setMouseTracking(False)
        self.pushButton_z1Up.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_z1Up.setAutoFillBackground(False)
        self.pushButton_z1Up.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_z1Up.setFlat(False)
        self.pushButton_z1Up.setObjectName("pushButton_z1Up")
        self.pushButton_z1down = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_z1down.setGeometry(QtCore.QRect(344, 370, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_z1down.setFont(font)
        self.pushButton_z1down.setMouseTracking(False)
        self.pushButton_z1down.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_z1down.setAutoFillBackground(False)
        self.pushButton_z1down.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_z1down.setFlat(False)
        self.pushButton_z1down.setObjectName("pushButton_z1down")
        self.pushButton_savePoint = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_savePoint.setGeometry(QtCore.QRect(330, 130, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_savePoint.setFont(font)
        self.pushButton_savePoint.setMouseTracking(False)
        self.pushButton_savePoint.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_savePoint.setAutoFillBackground(False)
        self.pushButton_savePoint.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_savePoint.setFlat(False)
        self.pushButton_savePoint.setObjectName("pushButton_savePoint")
        self.line_2 = QtWidgets.QFrame(self.frame_teachmode)
        self.line_2.setGeometry(QtCore.QRect(325, 290, 150, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame_teachmode)
        self.line_3.setGeometry(QtCore.QRect(480, 190, 3, 230))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_sprayOff = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_sprayOff.setGeometry(QtCore.QRect(490, 370, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_sprayOff.setFont(font)
        self.pushButton_sprayOff.setMouseTracking(False)
        self.pushButton_sprayOff.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_sprayOff.setAutoFillBackground(False)
        self.pushButton_sprayOff.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_sprayOff.setFlat(False)
        self.pushButton_sprayOff.setObjectName("pushButton_sprayOff")
        self.pushButton_sprayOn = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_sprayOn.setGeometry(QtCore.QRect(490, 310, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_sprayOn.setFont(font)
        self.pushButton_sprayOn.setMouseTracking(False)
        self.pushButton_sprayOn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_sprayOn.setAutoFillBackground(False)
        self.pushButton_sprayOn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_sprayOn.setFlat(False)
        self.pushButton_sprayOn.setObjectName("pushButton_sprayOn")
        self.pushButton_tableRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_tableRw.setGeometry(QtCore.QRect(490, 250, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_tableRw.setFont(font)
        self.pushButton_tableRw.setMouseTracking(False)
        self.pushButton_tableRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_tableRw.setAutoFillBackground(False)
        self.pushButton_tableRw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_tableRw.setFlat(False)
        self.pushButton_tableRw.setObjectName("pushButton_tableRw")
        self.pushButton_tableFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_tableFw.setGeometry(QtCore.QRect(490, 190, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_tableFw.setFont(font)
        self.pushButton_tableFw.setMouseTracking(False)
        self.pushButton_tableFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_tableFw.setAutoFillBackground(False)
        self.pushButton_tableFw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_tableFw.setFlat(False)
        self.pushButton_tableFw.setObjectName("pushButton_tableFw")
        self.lineEdit_speed = QtWidgets.QLineEdit(self.frame_teachmode)
        self.lineEdit_speed.setGeometry(QtCore.QRect(388, 210, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_speed.setFont(font)
        self.lineEdit_speed.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(236, 240, 241);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(255, 0, 0);\n"
"    color: rgb(39, 55, 70);\n"
"}")
        self.lineEdit_speed.setObjectName("lineEdit_speed")
        self.label_46 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_46.setGeometry(QtCore.QRect(330, 210, 51, 51))
        self.label_46.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_46.setObjectName("label_46")
        self.pushButton_saveFile = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_saveFile.setGeometry(QtCore.QRect(330, 70, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_saveFile.setFont(font)
        self.pushButton_saveFile.setMouseTracking(False)
        self.pushButton_saveFile.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_saveFile.setAutoFillBackground(False)
        self.pushButton_saveFile.setStyleSheet("QPushButton{\n"
"    background-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border-top-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(255, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(163, 228, 215);\n"
"}")
        self.pushButton_saveFile.setFlat(False)
        self.pushButton_saveFile.setObjectName("pushButton_saveFile")

        self.retranslateUi(teachMode)
        QtCore.QMetaObject.connectSlotsByName(teachMode)

    def retranslateUi(self, teachMode):
        _translate = QtCore.QCoreApplication.translate
        teachMode.setWindowTitle(_translate("teachMode", "TeachingMode"))
        self.label_39.setText(_translate("teachMode", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">TEACHING MODE</span></p></body></html>"))
        self.label_40.setText(_translate("teachMode", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X</span></p></body></html>"))
        self.label_41.setText(_translate("teachMode", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y</span></p></body></html>"))
        self.label_42.setText(_translate("teachMode", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Z</span></p></body></html>"))
        self.label_43.setText(_translate("teachMode", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">A</span></p></body></html>"))
        self.label_44.setText(_translate("teachMode", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">B</span></p></body></html>"))
        self.label_45.setText(_translate("teachMode", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">C</span></p></body></html>"))
        self.pushButton_xFw.setText(_translate("teachMode", "X-"))
        self.pushButton_xRw.setText(_translate("teachMode", "X+"))
        self.pushButton_yFw.setText(_translate("teachMode", "Y-"))
        self.pushButton_zFw.setText(_translate("teachMode", "Z-"))
        self.pushButton_aFw.setText(_translate("teachMode", "A-"))
        self.pushButton_bFw.setText(_translate("teachMode", "B-"))
        self.pushButton_cFw.setText(_translate("teachMode", "C-"))
        self.pushButton_yRw.setText(_translate("teachMode", "Y+"))
        self.pushButton_zRw.setText(_translate("teachMode", "Z+"))
        self.pushButton_aRw.setText(_translate("teachMode", "A+"))
        self.pushButton_bRw.setText(_translate("teachMode", "B+"))
        self.pushButton_cRw.setText(_translate("teachMode", "C+"))
        self.pushButton_z1Up.setText(_translate("teachMode", "Z1-"))
        self.pushButton_z1down.setText(_translate("teachMode", "Z1+"))
        self.pushButton_savePoint.setText(_translate("teachMode", "SET POINT"))
        self.pushButton_sprayOff.setText(_translate("teachMode", "SPRAY OFF"))
        self.pushButton_sprayOn.setText(_translate("teachMode", "SPRAY ON"))
        self.pushButton_tableRw.setText(_translate("teachMode", "TABLE RW"))
        self.pushButton_tableFw.setText(_translate("teachMode", "TABLE FW"))
        self.label_46.setText(_translate("teachMode", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">F%</span></p></body></html>"))
        self.pushButton_saveFile.setText(_translate("teachMode", "SAVE FILE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    teachMode = QtWidgets.QWidget()
    ui = Ui_teachMode()
    ui.setupUi(teachMode)
    teachMode.show()
    sys.exit(app.exec_())
