# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1915, 1026)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Robot.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame0 = QtWidgets.QFrame(self.centralwidget)
        self.frame0.setGeometry(QtCore.QRect(0, 0, 1921, 971))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame0.sizePolicy().hasHeightForWidth())
        self.frame0.setSizePolicy(sizePolicy)
        self.frame0.setMouseTracking(False)
        self.frame0.setTabletTracking(False)
        self.frame0.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.frame0.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame0.setLineWidth(2)
        self.frame0.setObjectName("frame0")
        self.frame_showtext = QtWidgets.QFrame(self.frame0)
        self.frame_showtext.setGeometry(QtCore.QRect(0, 0, 811, 941))
        self.frame_showtext.setStyleSheet("background-color: rgb(122, 122, 122);")
        self.frame_showtext.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_showtext.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_showtext.setLineWidth(2)
        self.frame_showtext.setObjectName("frame_showtext")
        self.textBrowser_showfile = QtWidgets.QTextBrowser(self.frame_showtext)
        self.textBrowser_showfile.setGeometry(QtCore.QRect(13, 78, 791, 711))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_showfile.setFont(font)
        self.textBrowser_showfile.setStyleSheet("background-color: rgb(195, 195, 195);\n"
"border: 3px solid  rgb(56, 56, 56);\n"
"border-radius: 10px")
        self.textBrowser_showfile.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_showfile.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_showfile.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textBrowser_showfile.setReadOnly(False)
        self.textBrowser_showfile.setOverwriteMode(True)
        self.textBrowser_showfile.setObjectName("textBrowser_showfile")
        self.label_showtime = QtWidgets.QLabel(self.frame_showtext)
        self.label_showtime.setGeometry(QtCore.QRect(704, 800, 101, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_showtime.setFont(font)
        self.label_showtime.setStyleSheet("background-color: rgb(195, 195, 195);\n"
"color: rgb(36, 36, 36);\n"
"border: 3px solid  rgb(56, 56, 56);\n"
"border-radius: 5px")
        self.label_showtime.setObjectName("label_showtime")
        self.label_showline = QtWidgets.QLabel(self.frame_showtext)
        self.label_showline.setGeometry(QtCore.QRect(13, 800, 691, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_showline.setFont(font)
        self.label_showline.setStyleSheet("background-color: rgb(195, 195, 195);\n"
"color: rgb(36, 36, 36);\n"
"border: 3px solid  rgb(56, 56, 56);\n"
"border-radius: 5px")
        self.label_showline.setObjectName("label_showline")
        self.label_directory = QtWidgets.QLabel(self.frame_showtext)
        self.label_directory.setGeometry(QtCore.QRect(13, 13, 791, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_directory.setFont(font)
        self.label_directory.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"font: 75 14pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid  rgb(56, 56, 56);\n"
"border-radius: 5px\n"
"")
        self.label_directory.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_directory.setObjectName("label_directory")
        self.pushButton_auto = QtWidgets.QPushButton(self.frame_showtext)
        self.pushButton_auto.setGeometry(QtCore.QRect(20, 880, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_auto.setFont(font)
        self.pushButton_auto.setMouseTracking(True)
        self.pushButton_auto.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_auto.setAutoFillBackground(False)
        self.pushButton_auto.setStyleSheet("background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_auto.setFlat(False)
        self.pushButton_auto.setObjectName("pushButton_auto")
        self.pushButton_jog = QtWidgets.QPushButton(self.frame_showtext)
        self.pushButton_jog.setGeometry(QtCore.QRect(170, 880, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_jog.setFont(font)
        self.pushButton_jog.setMouseTracking(True)
        self.pushButton_jog.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_jog.setAutoFillBackground(False)
        self.pushButton_jog.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_jog.setFlat(False)
        self.pushButton_jog.setObjectName("pushButton_jog")
        self.pushButton_estop = QtWidgets.QPushButton(self.frame_showtext)
        self.pushButton_estop.setGeometry(QtCore.QRect(470, 880, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_estop.setFont(font)
        self.pushButton_estop.setMouseTracking(True)
        self.pushButton_estop.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_estop.setAutoFillBackground(False)
        self.pushButton_estop.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_estop.setFlat(False)
        self.pushButton_estop.setObjectName("pushButton_estop")
        self.pushButton_pause = QtWidgets.QPushButton(self.frame_showtext)
        self.pushButton_pause.setGeometry(QtCore.QRect(320, 880, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_pause.setFont(font)
        self.pushButton_pause.setMouseTracking(True)
        self.pushButton_pause.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_pause.setAutoFillBackground(False)
        self.pushButton_pause.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_pause.setFlat(False)
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.frame_termial = QtWidgets.QFrame(self.frame0)
        self.frame_termial.setGeometry(QtCore.QRect(1360, 0, 561, 421))
        self.frame_termial.setStyleSheet("background-color: rgb(122, 122, 122);")
        self.frame_termial.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_termial.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_termial.setObjectName("frame_termial")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_termial)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textBrowser_terminal = QtWidgets.QTextBrowser(self.frame_termial)
        self.textBrowser_terminal.setStyleSheet("background-color:  rgb(77, 77, 77);\n"
"font: 75 14pt \"Arial\";\n"
"color: rgb(0, 250, 0);\n"
"border: 3px solid  rgb(56, 56, 56);\n"
"border-radius: 10px")
        self.textBrowser_terminal.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_terminal.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_terminal.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textBrowser_terminal.setReadOnly(True)
        self.textBrowser_terminal.setOverwriteMode(False)
        self.textBrowser_terminal.setObjectName("textBrowser_terminal")
        self.horizontalLayout_2.addWidget(self.textBrowser_terminal)
        self.frame_button = QtWidgets.QFrame(self.frame0)
        self.frame_button.setGeometry(QtCore.QRect(820, 430, 1101, 61))
        self.frame_button.setStyleSheet("background-color: rgb(122, 122, 122);")
        self.frame_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button.setObjectName("frame_button")
        self.pushButton_teach = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_teach.setGeometry(QtCore.QRect(180, 5, 161, 50))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_teach.setFont(font)
        self.pushButton_teach.setMouseTracking(False)
        self.pushButton_teach.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_teach.setAutoFillBackground(False)
        self.pushButton_teach.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.pushButton_teach.setObjectName("pushButton_teach")
        self.pushButton_settings = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_settings.setGeometry(QtCore.QRect(350, 5, 161, 50))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_settings.setFont(font)
        self.pushButton_settings.setMouseTracking(False)
        self.pushButton_settings.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_settings.setAutoFillBackground(False)
        self.pushButton_settings.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.pushButton_settings.setObjectName("pushButton_settings")
        self.pushButton_gotozero = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_gotozero.setGeometry(QtCore.QRect(690, 5, 161, 50))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_gotozero.setFont(font)
        self.pushButton_gotozero.setMouseTracking(False)
        self.pushButton_gotozero.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_gotozero.setAutoFillBackground(False)
        self.pushButton_gotozero.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.pushButton_gotozero.setObjectName("pushButton_gotozero")
        self.pushButton_machinehome = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_machinehome.setGeometry(QtCore.QRect(860, 5, 231, 50))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_machinehome.setFont(font)
        self.pushButton_machinehome.setMouseTracking(False)
        self.pushButton_machinehome.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_machinehome.setAutoFillBackground(False)
        self.pushButton_machinehome.setStyleSheet("background-color: rgb(173, 51, 10);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.pushButton_machinehome.setObjectName("pushButton_machinehome")
        self.pushButton_choosefile = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_choosefile.setGeometry(QtCore.QRect(10, 5, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_choosefile.setFont(font)
        self.pushButton_choosefile.setMouseTracking(False)
        self.pushButton_choosefile.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_choosefile.setAutoFillBackground(False)
        self.pushButton_choosefile.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"pressed { background-color: rgb(200,0,0)};\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);\n"
"hover:  {background-color: rgb(200,0,0)};")
        self.pushButton_choosefile.setFlat(False)
        self.pushButton_choosefile.setObjectName("pushButton_choosefile")
        self.pushButton_manual = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_manual.setGeometry(QtCore.QRect(520, 5, 161, 50))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_manual.setFont(font)
        self.pushButton_manual.setMouseTracking(False)
        self.pushButton_manual.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_manual.setAutoFillBackground(False)
        self.pushButton_manual.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.pushButton_manual.setObjectName("pushButton_manual")
        self.frame_position = QtWidgets.QFrame(self.frame0)
        self.frame_position.setGeometry(QtCore.QRect(1430, 510, 481, 431))
        self.frame_position.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.frame_position.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_position.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_position.setObjectName("frame_position")
        self.label = QtWidgets.QLabel(self.frame_position)
        self.label.setGeometry(QtCore.QRect(10, 10, 461, 51))
        self.label.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_position)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 61, 51))
        self.label_2.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_position)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 61, 51))
        self.label_3.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_position)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 61, 51))
        self.label_4.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_position)
        self.label_5.setGeometry(QtCore.QRect(10, 250, 61, 51))
        self.label_5.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_position)
        self.label_6.setGeometry(QtCore.QRect(10, 310, 61, 51))
        self.label_6.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_position)
        self.label_7.setGeometry(QtCore.QRect(10, 370, 61, 51))
        self.label_7.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_7.setObjectName("label_7")
        self.label_Xposition = QtWidgets.QLabel(self.frame_position)
        self.label_Xposition.setGeometry(QtCore.QRect(80, 70, 191, 51))
        self.label_Xposition.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Xposition.setObjectName("label_Xposition")
        self.label_Xhome = QtWidgets.QLabel(self.frame_position)
        self.label_Xhome.setGeometry(QtCore.QRect(280, 70, 191, 51))
        self.label_Xhome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Xhome.setObjectName("label_Xhome")
        self.label_Yposition = QtWidgets.QLabel(self.frame_position)
        self.label_Yposition.setGeometry(QtCore.QRect(80, 130, 191, 51))
        self.label_Yposition.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Yposition.setObjectName("label_Yposition")
        self.label_Yhome = QtWidgets.QLabel(self.frame_position)
        self.label_Yhome.setGeometry(QtCore.QRect(280, 130, 191, 51))
        self.label_Yhome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Yhome.setObjectName("label_Yhome")
        self.label_Zposition = QtWidgets.QLabel(self.frame_position)
        self.label_Zposition.setGeometry(QtCore.QRect(80, 190, 191, 51))
        self.label_Zposition.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Zposition.setObjectName("label_Zposition")
        self.label_Aposition = QtWidgets.QLabel(self.frame_position)
        self.label_Aposition.setGeometry(QtCore.QRect(80, 250, 191, 51))
        self.label_Aposition.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Aposition.setObjectName("label_Aposition")
        self.label_Bposition = QtWidgets.QLabel(self.frame_position)
        self.label_Bposition.setGeometry(QtCore.QRect(80, 310, 191, 51))
        self.label_Bposition.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Bposition.setObjectName("label_Bposition")
        self.label_Cposition = QtWidgets.QLabel(self.frame_position)
        self.label_Cposition.setGeometry(QtCore.QRect(80, 370, 191, 51))
        self.label_Cposition.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Cposition.setObjectName("label_Cposition")
        self.label_Zhome = QtWidgets.QLabel(self.frame_position)
        self.label_Zhome.setGeometry(QtCore.QRect(280, 190, 191, 51))
        self.label_Zhome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Zhome.setObjectName("label_Zhome")
        self.label_Ahome = QtWidgets.QLabel(self.frame_position)
        self.label_Ahome.setGeometry(QtCore.QRect(280, 250, 191, 51))
        self.label_Ahome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Ahome.setObjectName("label_Ahome")
        self.label_Bhome = QtWidgets.QLabel(self.frame_position)
        self.label_Bhome.setGeometry(QtCore.QRect(280, 310, 191, 51))
        self.label_Bhome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Bhome.setObjectName("label_Bhome")
        self.label_Chome = QtWidgets.QLabel(self.frame_position)
        self.label_Chome.setGeometry(QtCore.QRect(280, 370, 191, 51))
        self.label_Chome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Chome.setObjectName("label_Chome")
        self.frame_teachmode = QtWidgets.QFrame(self.frame0)
        self.frame_teachmode.setGeometry(QtCore.QRect(820, 510, 601, 431))
        self.frame_teachmode.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.frame_teachmode.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_teachmode.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_teachmode.setObjectName("frame_teachmode")
        self.label_39 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_39.setGeometry(QtCore.QRect(10, 10, 461, 51))
        self.label_39.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_40.setGeometry(QtCore.QRect(10, 70, 61, 51))
        self.label_40.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_41.setGeometry(QtCore.QRect(10, 130, 61, 51))
        self.label_41.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_42.setGeometry(QtCore.QRect(10, 190, 61, 51))
        self.label_42.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_43.setGeometry(QtCore.QRect(10, 250, 61, 51))
        self.label_43.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_44.setGeometry(QtCore.QRect(10, 310, 61, 51))
        self.label_44.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_45.setGeometry(QtCore.QRect(10, 370, 61, 51))
        self.label_45.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_45.setObjectName("label_45")
        self.pushButton_xFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_xFw.setGeometry(QtCore.QRect(80, 70, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_xFw.setFont(font)
        self.pushButton_xFw.setMouseTracking(True)
        self.pushButton_xFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_xFw.setAutoFillBackground(False)
        self.pushButton_xFw.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_xFw.setFlat(False)
        self.pushButton_xFw.setObjectName("pushButton_xFw")
        self.pushButton_xRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_xRw.setGeometry(QtCore.QRect(200, 70, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_xRw.setFont(font)
        self.pushButton_xRw.setMouseTracking(False)
        self.pushButton_xRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_xRw.setAutoFillBackground(False)
        self.pushButton_xRw.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_xRw.setFlat(False)
        self.pushButton_xRw.setObjectName("pushButton_xRw")
        self.pushButton_yFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_yFw.setGeometry(QtCore.QRect(80, 130, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_yFw.setFont(font)
        self.pushButton_yFw.setMouseTracking(False)
        self.pushButton_yFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_yFw.setAutoFillBackground(False)
        self.pushButton_yFw.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_yFw.setFlat(False)
        self.pushButton_yFw.setObjectName("pushButton_yFw")
        self.pushButton_zFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_zFw.setGeometry(QtCore.QRect(80, 190, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_zFw.setFont(font)
        self.pushButton_zFw.setMouseTracking(False)
        self.pushButton_zFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_zFw.setAutoFillBackground(False)
        self.pushButton_zFw.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_zFw.setFlat(False)
        self.pushButton_zFw.setObjectName("pushButton_zFw")
        self.pushButton_aFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_aFw.setGeometry(QtCore.QRect(80, 250, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_aFw.setFont(font)
        self.pushButton_aFw.setMouseTracking(False)
        self.pushButton_aFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_aFw.setAutoFillBackground(False)
        self.pushButton_aFw.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_aFw.setFlat(False)
        self.pushButton_aFw.setObjectName("pushButton_aFw")
        self.pushButton_bFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_bFw.setGeometry(QtCore.QRect(80, 310, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_bFw.setFont(font)
        self.pushButton_bFw.setMouseTracking(False)
        self.pushButton_bFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_bFw.setAutoFillBackground(False)
        self.pushButton_bFw.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_bFw.setFlat(False)
        self.pushButton_bFw.setObjectName("pushButton_bFw")
        self.pushButton_cFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_cFw.setGeometry(QtCore.QRect(80, 370, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_cFw.setFont(font)
        self.pushButton_cFw.setMouseTracking(False)
        self.pushButton_cFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_cFw.setAutoFillBackground(False)
        self.pushButton_cFw.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_cFw.setFlat(False)
        self.pushButton_cFw.setObjectName("pushButton_cFw")
        self.pushButton_yRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_yRw.setGeometry(QtCore.QRect(200, 130, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_yRw.setFont(font)
        self.pushButton_yRw.setMouseTracking(False)
        self.pushButton_yRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_yRw.setAutoFillBackground(False)
        self.pushButton_yRw.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_yRw.setFlat(False)
        self.pushButton_yRw.setObjectName("pushButton_yRw")
        self.pushButton_zRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_zRw.setGeometry(QtCore.QRect(200, 190, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_zRw.setFont(font)
        self.pushButton_zRw.setMouseTracking(False)
        self.pushButton_zRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_zRw.setAutoFillBackground(False)
        self.pushButton_zRw.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_zRw.setFlat(False)
        self.pushButton_zRw.setObjectName("pushButton_zRw")
        self.pushButton_aRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_aRw.setGeometry(QtCore.QRect(200, 250, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_aRw.setFont(font)
        self.pushButton_aRw.setMouseTracking(False)
        self.pushButton_aRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_aRw.setAutoFillBackground(False)
        self.pushButton_aRw.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_aRw.setFlat(False)
        self.pushButton_aRw.setObjectName("pushButton_aRw")
        self.pushButton_bRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_bRw.setGeometry(QtCore.QRect(200, 310, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_bRw.setFont(font)
        self.pushButton_bRw.setMouseTracking(False)
        self.pushButton_bRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_bRw.setAutoFillBackground(False)
        self.pushButton_bRw.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_bRw.setFlat(False)
        self.pushButton_bRw.setObjectName("pushButton_bRw")
        self.pushButton_cRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_cRw.setGeometry(QtCore.QRect(200, 370, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_cRw.setFont(font)
        self.pushButton_cRw.setMouseTracking(False)
        self.pushButton_cRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_cRw.setAutoFillBackground(False)
        self.pushButton_cRw.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_cRw.setFlat(False)
        self.pushButton_cRw.setObjectName("pushButton_cRw")
        self.line = QtWidgets.QFrame(self.frame_teachmode)
        self.line.setGeometry(QtCore.QRect(320, 70, 3, 351))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_z1Up = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_z1Up.setGeometry(QtCore.QRect(344, 310, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_z1Up.setFont(font)
        self.pushButton_z1Up.setMouseTracking(False)
        self.pushButton_z1Up.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_z1Up.setAutoFillBackground(False)
        self.pushButton_z1Up.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_z1Up.setFlat(False)
        self.pushButton_z1Up.setObjectName("pushButton_z1Up")
        self.pushButton_z1down = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_z1down.setGeometry(QtCore.QRect(344, 370, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_z1down.setFont(font)
        self.pushButton_z1down.setMouseTracking(False)
        self.pushButton_z1down.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_z1down.setAutoFillBackground(False)
        self.pushButton_z1down.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_z1down.setFlat(False)
        self.pushButton_z1down.setObjectName("pushButton_z1down")
        self.pushButton_savePoint = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_savePoint.setGeometry(QtCore.QRect(330, 70, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_savePoint.setFont(font)
        self.pushButton_savePoint.setMouseTracking(False)
        self.pushButton_savePoint.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_savePoint.setAutoFillBackground(False)
        self.pushButton_savePoint.setStyleSheet("background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_savePoint.setFlat(False)
        self.pushButton_savePoint.setObjectName("pushButton_savePoint")
        self.pushButton_setZero = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_setZero.setGeometry(QtCore.QRect(330, 150, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_setZero.setFont(font)
        self.pushButton_setZero.setMouseTracking(False)
        self.pushButton_setZero.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_setZero.setAutoFillBackground(False)
        self.pushButton_setZero.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_setZero.setFlat(False)
        self.pushButton_setZero.setObjectName("pushButton_setZero")
        self.pushButton_exitTeach = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_exitTeach.setGeometry(QtCore.QRect(480, 10, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_exitTeach.setFont(font)
        self.pushButton_exitTeach.setMouseTracking(False)
        self.pushButton_exitTeach.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_exitTeach.setAutoFillBackground(False)
        self.pushButton_exitTeach.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_exitTeach.setFlat(False)
        self.pushButton_exitTeach.setObjectName("pushButton_exitTeach")
        self.line_2 = QtWidgets.QFrame(self.frame_teachmode)
        self.line_2.setGeometry(QtCore.QRect(325, 300, 150, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame_teachmode)
        self.line_3.setGeometry(QtCore.QRect(480, 70, 3, 351))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_sprayOff = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_sprayOff.setGeometry(QtCore.QRect(490, 370, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_sprayOff.setFont(font)
        self.pushButton_sprayOff.setMouseTracking(False)
        self.pushButton_sprayOff.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_sprayOff.setAutoFillBackground(False)
        self.pushButton_sprayOff.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_sprayOff.setFlat(False)
        self.pushButton_sprayOff.setObjectName("pushButton_sprayOff")
        self.pushButton_sprayOn = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_sprayOn.setGeometry(QtCore.QRect(490, 310, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_sprayOn.setFont(font)
        self.pushButton_sprayOn.setMouseTracking(False)
        self.pushButton_sprayOn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_sprayOn.setAutoFillBackground(False)
        self.pushButton_sprayOn.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_sprayOn.setFlat(False)
        self.pushButton_sprayOn.setObjectName("pushButton_sprayOn")
        self.pushButton_tableRw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_tableRw.setGeometry(QtCore.QRect(490, 250, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_tableRw.setFont(font)
        self.pushButton_tableRw.setMouseTracking(False)
        self.pushButton_tableRw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_tableRw.setAutoFillBackground(False)
        self.pushButton_tableRw.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_tableRw.setFlat(False)
        self.pushButton_tableRw.setObjectName("pushButton_tableRw")
        self.pushButton_tableFw = QtWidgets.QPushButton(self.frame_teachmode)
        self.pushButton_tableFw.setGeometry(QtCore.QRect(490, 190, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_tableFw.setFont(font)
        self.pushButton_tableFw.setMouseTracking(False)
        self.pushButton_tableFw.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_tableFw.setAutoFillBackground(False)
        self.pushButton_tableFw.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_tableFw.setFlat(False)
        self.pushButton_tableFw.setObjectName("pushButton_tableFw")
        self.lineEdit_speed = QtWidgets.QLineEdit(self.frame_teachmode)
        self.lineEdit_speed.setGeometry(QtCore.QRect(388, 230, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_speed.setFont(font)
        self.lineEdit_speed.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_speed.setObjectName("lineEdit_speed")
        self.label_46 = QtWidgets.QLabel(self.frame_teachmode)
        self.label_46.setGeometry(QtCore.QRect(330, 230, 51, 51))
        self.label_46.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_46.setObjectName("label_46")
        self.frame = QtWidgets.QFrame(self.frame0)
        self.frame.setGeometry(QtCore.QRect(820, 10, 531, 411))
        self.frame.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalSlider_speedMotor = QtWidgets.QSlider(self.frame)
        self.verticalSlider_speedMotor.setGeometry(QtCore.QRect(475, 70, 22, 321))
        self.verticalSlider_speedMotor.setMinimum(30)
        self.verticalSlider_speedMotor.setMaximum(200)
        self.verticalSlider_speedMotor.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_speedMotor.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.verticalSlider_speedMotor.setTickInterval(1)
        self.verticalSlider_speedMotor.setObjectName("verticalSlider_speedMotor")
        self.verticalSlider_spray = QtWidgets.QSlider(self.frame)
        self.verticalSlider_spray.setGeometry(QtCore.QRect(395, 70, 22, 321))
        self.verticalSlider_spray.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_spray.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.verticalSlider_spray.setTickInterval(1)
        self.verticalSlider_spray.setObjectName("verticalSlider_spray")
        self.label_x1 = QtWidgets.QLabel(self.frame)
        self.label_x1.setGeometry(QtCore.QRect(10, 10, 61, 31))
        self.label_x1.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x1.setObjectName("label_x1")
        self.label_x2 = QtWidgets.QLabel(self.frame)
        self.label_x2.setGeometry(QtCore.QRect(10, 60, 61, 31))
        self.label_x2.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x2.setObjectName("label_x2")
        self.label_x3 = QtWidgets.QLabel(self.frame)
        self.label_x3.setGeometry(QtCore.QRect(10, 110, 61, 31))
        self.label_x3.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x3.setObjectName("label_x3")
        self.label_x4 = QtWidgets.QLabel(self.frame)
        self.label_x4.setGeometry(QtCore.QRect(10, 160, 61, 31))
        self.label_x4.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x4.setObjectName("label_x4")
        self.label_x5 = QtWidgets.QLabel(self.frame)
        self.label_x5.setGeometry(QtCore.QRect(10, 210, 61, 31))
        self.label_x5.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x5.setObjectName("label_x5")
        self.label_x6 = QtWidgets.QLabel(self.frame)
        self.label_x6.setGeometry(QtCore.QRect(10, 260, 61, 31))
        self.label_x6.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x6.setObjectName("label_x6")
        self.label_x7 = QtWidgets.QLabel(self.frame)
        self.label_x7.setGeometry(QtCore.QRect(10, 310, 61, 31))
        self.label_x7.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x7.setObjectName("label_x7")
        self.label_x8 = QtWidgets.QLabel(self.frame)
        self.label_x8.setGeometry(QtCore.QRect(10, 360, 61, 31))
        self.label_x8.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x8.setObjectName("label_x8")
        self.label_x9 = QtWidgets.QLabel(self.frame)
        self.label_x9.setGeometry(QtCore.QRect(80, 10, 61, 31))
        self.label_x9.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x9.setObjectName("label_x9")
        self.label_x10 = QtWidgets.QLabel(self.frame)
        self.label_x10.setGeometry(QtCore.QRect(80, 60, 61, 31))
        self.label_x10.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x10.setObjectName("label_x10")
        self.label_x11 = QtWidgets.QLabel(self.frame)
        self.label_x11.setGeometry(QtCore.QRect(80, 110, 61, 31))
        self.label_x11.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x11.setObjectName("label_x11")
        self.label_x12 = QtWidgets.QLabel(self.frame)
        self.label_x12.setGeometry(QtCore.QRect(80, 160, 61, 31))
        self.label_x12.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x12.setObjectName("label_x12")
        self.label_x13 = QtWidgets.QLabel(self.frame)
        self.label_x13.setGeometry(QtCore.QRect(80, 210, 61, 31))
        self.label_x13.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x13.setObjectName("label_x13")
        self.label_x14 = QtWidgets.QLabel(self.frame)
        self.label_x14.setGeometry(QtCore.QRect(80, 260, 61, 31))
        self.label_x14.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x14.setObjectName("label_x14")
        self.label_x15 = QtWidgets.QLabel(self.frame)
        self.label_x15.setGeometry(QtCore.QRect(80, 310, 61, 31))
        self.label_x15.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x15.setObjectName("label_x15")
        self.label_x16 = QtWidgets.QLabel(self.frame)
        self.label_x16.setGeometry(QtCore.QRect(80, 360, 61, 31))
        self.label_x16.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x16.setObjectName("label_x16")
        self.label_y1 = QtWidgets.QLabel(self.frame)
        self.label_y1.setGeometry(QtCore.QRect(180, 10, 61, 31))
        self.label_y1.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y1.setObjectName("label_y1")
        self.label_y9 = QtWidgets.QLabel(self.frame)
        self.label_y9.setGeometry(QtCore.QRect(280, 10, 61, 31))
        self.label_y9.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y9.setObjectName("label_y9")
        self.label_y2 = QtWidgets.QLabel(self.frame)
        self.label_y2.setGeometry(QtCore.QRect(180, 60, 61, 31))
        self.label_y2.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y2.setObjectName("label_y2")
        self.label_y3 = QtWidgets.QLabel(self.frame)
        self.label_y3.setGeometry(QtCore.QRect(180, 110, 61, 31))
        self.label_y3.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y3.setObjectName("label_y3")
        self.label_y4 = QtWidgets.QLabel(self.frame)
        self.label_y4.setGeometry(QtCore.QRect(180, 160, 61, 31))
        self.label_y4.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y4.setObjectName("label_y4")
        self.label_y5 = QtWidgets.QLabel(self.frame)
        self.label_y5.setGeometry(QtCore.QRect(180, 210, 61, 31))
        self.label_y5.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y5.setObjectName("label_y5")
        self.label_y6 = QtWidgets.QLabel(self.frame)
        self.label_y6.setGeometry(QtCore.QRect(180, 260, 61, 31))
        self.label_y6.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y6.setObjectName("label_y6")
        self.label_y7 = QtWidgets.QLabel(self.frame)
        self.label_y7.setGeometry(QtCore.QRect(180, 310, 61, 31))
        self.label_y7.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y7.setObjectName("label_y7")
        self.label_y8 = QtWidgets.QLabel(self.frame)
        self.label_y8.setGeometry(QtCore.QRect(180, 360, 61, 31))
        self.label_y8.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y8.setObjectName("label_y8")
        self.label_y10 = QtWidgets.QLabel(self.frame)
        self.label_y10.setGeometry(QtCore.QRect(280, 60, 61, 31))
        self.label_y10.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y10.setObjectName("label_y10")
        self.label_y11 = QtWidgets.QLabel(self.frame)
        self.label_y11.setGeometry(QtCore.QRect(280, 110, 61, 31))
        self.label_y11.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y11.setObjectName("label_y11")
        self.label_y12 = QtWidgets.QLabel(self.frame)
        self.label_y12.setGeometry(QtCore.QRect(280, 160, 61, 31))
        self.label_y12.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y12.setObjectName("label_y12")
        self.label_y13 = QtWidgets.QLabel(self.frame)
        self.label_y13.setGeometry(QtCore.QRect(280, 210, 61, 31))
        self.label_y13.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y13.setObjectName("label_y13")
        self.label_y14 = QtWidgets.QLabel(self.frame)
        self.label_y14.setGeometry(QtCore.QRect(280, 260, 61, 31))
        self.label_y14.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y14.setObjectName("label_y14")
        self.label_y15 = QtWidgets.QLabel(self.frame)
        self.label_y15.setGeometry(QtCore.QRect(280, 310, 61, 31))
        self.label_y15.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y15.setObjectName("label_y15")
        self.label_y16 = QtWidgets.QLabel(self.frame)
        self.label_y16.setGeometry(QtCore.QRect(280, 360, 61, 31))
        self.label_y16.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y16.setObjectName("label_y16")
        self.radioButtonY1 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY1.setGeometry(QtCore.QRect(150, 10, 21, 20))
        self.radioButtonY1.setObjectName("radioButtonY1")
        self.radioButtonY2 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY2.setGeometry(QtCore.QRect(150, 60, 21, 20))
        self.radioButtonY2.setObjectName("radioButtonY2")
        self.radioButtonY3 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY3.setGeometry(QtCore.QRect(150, 110, 21, 20))
        self.radioButtonY3.setObjectName("radioButtonY3")
        self.radioButtonY4 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY4.setGeometry(QtCore.QRect(150, 160, 21, 20))
        self.radioButtonY4.setObjectName("radioButtonY4")
        self.radioButtonY5 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY5.setGeometry(QtCore.QRect(150, 210, 21, 20))
        self.radioButtonY5.setObjectName("radioButtonY5")
        self.radioButtonY6 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY6.setGeometry(QtCore.QRect(150, 260, 21, 20))
        self.radioButtonY6.setObjectName("radioButtonY6")
        self.radioButtonY7 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY7.setGeometry(QtCore.QRect(150, 310, 21, 20))
        self.radioButtonY7.setObjectName("radioButtonY7")
        self.radioButtonY8 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY8.setGeometry(QtCore.QRect(150, 360, 21, 20))
        self.radioButtonY8.setObjectName("radioButtonY8")
        self.radioButtonY9 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY9.setGeometry(QtCore.QRect(250, 10, 21, 20))
        self.radioButtonY9.setObjectName("radioButtonY9")
        self.radioButtonY10 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY10.setGeometry(QtCore.QRect(250, 60, 21, 20))
        self.radioButtonY10.setObjectName("radioButtonY10")
        self.radioButtonY11 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY11.setGeometry(QtCore.QRect(250, 110, 21, 20))
        self.radioButtonY11.setObjectName("radioButtonY11")
        self.radioButtonY12 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY12.setGeometry(QtCore.QRect(250, 160, 21, 20))
        self.radioButtonY12.setObjectName("radioButtonY12")
        self.radioButtonY13 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY13.setGeometry(QtCore.QRect(250, 210, 21, 20))
        self.radioButtonY13.setObjectName("radioButtonY13")
        self.radioButtonY14 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY14.setGeometry(QtCore.QRect(250, 260, 21, 20))
        self.radioButtonY14.setObjectName("radioButtonY14")
        self.radioButtonY15 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY15.setGeometry(QtCore.QRect(250, 310, 21, 20))
        self.radioButtonY15.setObjectName("radioButtonY15")
        self.radioButtonY16 = QtWidgets.QRadioButton(self.frame)
        self.radioButtonY16.setGeometry(QtCore.QRect(250, 360, 21, 20))
        self.radioButtonY16.setObjectName("radioButtonY16")
        self.value_speedSpray = QtWidgets.QLabel(self.frame)
        self.value_speedSpray.setGeometry(QtCore.QRect(370, 30, 71, 31))
        self.value_speedSpray.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.value_speedSpray.setObjectName("value_speedSpray")
        self.label_speedMotor = QtWidgets.QLabel(self.frame)
        self.label_speedMotor.setGeometry(QtCore.QRect(450, 30, 71, 31))
        self.label_speedMotor.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_speedMotor.setObjectName("label_speedMotor")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1915, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuComunication = QtWidgets.QMenu(self.menubar)
        self.menuComunication.setObjectName("menuComunication")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuAbout_2 = QtWidgets.QMenu(self.menubar)
        self.menuAbout_2.setObjectName("menuAbout_2")
        self.menuAbout_3 = QtWidgets.QMenu(self.menubar)
        self.menuAbout_3.setObjectName("menuAbout_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionChoose_File_pnt = QtWidgets.QAction(MainWindow)
        self.actionChoose_File_pnt.setObjectName("actionChoose_File_pnt")
        self.actionSave_file = QtWidgets.QAction(MainWindow)
        self.actionSave_file.setObjectName("actionSave_file")
        self.actionMotor = QtWidgets.QAction(MainWindow)
        self.actionMotor.setObjectName("actionMotor")
        self.actionTeach_mode = QtWidgets.QAction(MainWindow)
        self.actionTeach_mode.setObjectName("actionTeach_mode")
        self.actionAbout_Machine = QtWidgets.QAction(MainWindow)
        self.actionAbout_Machine.setObjectName("actionAbout_Machine")
        self.actionContact = QtWidgets.QAction(MainWindow)
        self.actionContact.setObjectName("actionContact")
        self.actionConnect_to_Slave = QtWidgets.QAction(MainWindow)
        self.actionConnect_to_Slave.setObjectName("actionConnect_to_Slave")
        self.actionAbout_Machine_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_Machine_2.setObjectName("actionAbout_Machine_2")
        self.actionContact_2 = QtWidgets.QAction(MainWindow)
        self.actionContact_2.setObjectName("actionContact_2")
        self.actionAbout_Machine_3 = QtWidgets.QAction(MainWindow)
        self.actionAbout_Machine_3.setObjectName("actionAbout_Machine_3")
        self.actionContact_3 = QtWidgets.QAction(MainWindow)
        self.actionContact_3.setObjectName("actionContact_3")
        self.menuFile.addAction(self.actionChoose_File_pnt)
        self.menuFile.addAction(self.actionSave_file)
        self.menuSetting.addAction(self.actionMotor)
        self.menuComunication.addAction(self.actionConnect_to_Slave)
        self.menuAbout.addAction(self.actionAbout_Machine)
        self.menuAbout_3.addAction(self.actionAbout_Machine_3)
        self.menuAbout_3.addAction(self.actionContact_3)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuComunication.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuAbout_2.menuAction())
        self.menubar.addAction(self.menuAbout_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RoyalRobotics - Khoi Nguyen Plastic.jsc - Automatic Painting Machine"))
        self.label_showtime.setText(_translate("MainWindow", "0:00:00"))
        self.label_showline.setText(_translate("MainWindow", "Show line"))
        self.label_directory.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">NO FILE LOADED</span></p></body></html>"))
        self.pushButton_auto.setText(_translate("MainWindow", "AUTO"))
        self.pushButton_jog.setText(_translate("MainWindow", "JOG"))
        self.pushButton_estop.setText(_translate("MainWindow", "E-STOP"))
        self.pushButton_pause.setText(_translate("MainWindow", "PAUSE"))
        self.pushButton_teach.setText(_translate("MainWindow", "TEACH MODE"))
        self.pushButton_settings.setText(_translate("MainWindow", "SETTINGS"))
        self.pushButton_gotozero.setText(_translate("MainWindow", "GO TO ZERO"))
        self.pushButton_machinehome.setText(_translate("MainWindow", "MACHINE HOME"))
        self.pushButton_choosefile.setText(_translate("MainWindow", "CHOOSE FILE"))
        self.pushButton_manual.setText(_translate("MainWindow", "MANUAL"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">AXIS ---- G54WORK ------ MACHINE</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Z</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">A</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">B</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">C</span></p></body></html>"))
        self.label_Xposition.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Xhome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Yposition.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Yhome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Zposition.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Aposition.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Bposition.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Cposition.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Zhome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Ahome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Bhome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Chome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">TEACHING MODE</span></p></body></html>"))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X</span></p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y</span></p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Z</span></p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">A</span></p></body></html>"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">B</span></p></body></html>"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">C</span></p></body></html>"))
        self.pushButton_xFw.setText(_translate("MainWindow", "X+"))
        self.pushButton_xRw.setText(_translate("MainWindow", "X-"))
        self.pushButton_yFw.setText(_translate("MainWindow", "Y+"))
        self.pushButton_zFw.setText(_translate("MainWindow", "Z+"))
        self.pushButton_aFw.setText(_translate("MainWindow", "A+"))
        self.pushButton_bFw.setText(_translate("MainWindow", "B+"))
        self.pushButton_cFw.setText(_translate("MainWindow", "C+"))
        self.pushButton_yRw.setText(_translate("MainWindow", "Y-"))
        self.pushButton_zRw.setText(_translate("MainWindow", "Z-"))
        self.pushButton_aRw.setText(_translate("MainWindow", "A-"))
        self.pushButton_bRw.setText(_translate("MainWindow", "B-"))
        self.pushButton_cRw.setText(_translate("MainWindow", "C-"))
        self.pushButton_z1Up.setText(_translate("MainWindow", "Z1+"))
        self.pushButton_z1down.setText(_translate("MainWindow", "Z1-"))
        self.pushButton_savePoint.setText(_translate("MainWindow", "SAVE POINT"))
        self.pushButton_setZero.setText(_translate("MainWindow", "SET ZERO"))
        self.pushButton_exitTeach.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_sprayOff.setText(_translate("MainWindow", "SPRAY OFF"))
        self.pushButton_sprayOn.setText(_translate("MainWindow", "SPRAY ON"))
        self.pushButton_tableRw.setText(_translate("MainWindow", "TABLE RW"))
        self.pushButton_tableFw.setText(_translate("MainWindow", "TABLE FW"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">F%</span></p></body></html>"))
        self.label_x1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X1</span></p></body></html>"))
        self.label_x2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X2</span></p></body></html>"))
        self.label_x3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X3</span></p></body></html>"))
        self.label_x4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X4</span></p></body></html>"))
        self.label_x5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X5</span></p></body></html>"))
        self.label_x6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X6</span></p></body></html>"))
        self.label_x7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X7</span></p></body></html>"))
        self.label_x8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X8</span></p></body></html>"))
        self.label_x9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X9</span></p></body></html>"))
        self.label_x10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X10</span></p></body></html>"))
        self.label_x11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X11</span></p></body></html>"))
        self.label_x12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X12</span></p></body></html>"))
        self.label_x13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X13</span></p></body></html>"))
        self.label_x14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X14</span></p></body></html>"))
        self.label_x15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X15</span></p></body></html>"))
        self.label_x16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X16</span></p></body></html>"))
        self.label_y1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y1</span></p></body></html>"))
        self.label_y9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y9</span></p></body></html>"))
        self.label_y2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y2</span></p></body></html>"))
        self.label_y3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y3</span></p></body></html>"))
        self.label_y4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y4</span></p></body></html>"))
        self.label_y5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y5</span></p></body></html>"))
        self.label_y6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y6</span></p></body></html>"))
        self.label_y7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y7</span></p></body></html>"))
        self.label_y8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y8</span></p></body></html>"))
        self.label_y10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y10</span></p></body></html>"))
        self.label_y11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y11</span></p></body></html>"))
        self.label_y12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y12</span></p></body></html>"))
        self.label_y13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y13</span></p></body></html>"))
        self.label_y14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y14</span></p></body></html>"))
        self.label_y15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y15</span></p></body></html>"))
        self.label_y16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y16</span></p></body></html>"))
        self.radioButtonY1.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY2.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY3.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY4.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY5.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY6.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY7.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY8.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY9.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY10.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY11.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY12.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY13.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY14.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY15.setText(_translate("MainWindow", "RadioButton"))
        self.radioButtonY16.setText(_translate("MainWindow", "RadioButton"))
        self.value_speedSpray.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_speedMotor.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "FILE"))
        self.menuSetting.setTitle(_translate("MainWindow", "SETTINGS"))
        self.menuComunication.setTitle(_translate("MainWindow", "COMMUNICATION"))
        self.menuAbout.setTitle(_translate("MainWindow", "MANUAL"))
        self.menuAbout_2.setTitle(_translate("MainWindow", "TEACH MODE"))
        self.menuAbout_3.setTitle(_translate("MainWindow", "ABOUT"))
        self.actionChoose_File_pnt.setText(_translate("MainWindow", "Choose file (.pnt)"))
        self.actionSave_file.setText(_translate("MainWindow", "Save file"))
        self.actionMotor.setText(_translate("MainWindow", "Motor"))
        self.actionTeach_mode.setText(_translate("MainWindow", "Teach mode"))
        self.actionAbout_Machine.setText(_translate("MainWindow", "Toggle coil Y"))
        self.actionContact.setText(_translate("MainWindow", "Contact"))
        self.actionConnect_to_Slave.setText(_translate("MainWindow", "Connect to Slave"))
        self.actionAbout_Machine_2.setText(_translate("MainWindow", "About Machine"))
        self.actionContact_2.setText(_translate("MainWindow", "Contact"))
        self.actionAbout_Machine_3.setText(_translate("MainWindow", "About Machine"))
        self.actionContact_3.setText(_translate("MainWindow", "Contact"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
