# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 690)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1250, 690))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Robot.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame0 = QtWidgets.QFrame(self.centralwidget)
        self.frame0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame0.sizePolicy().hasHeightForWidth())
        self.frame0.setSizePolicy(sizePolicy)
        self.frame0.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.frame0.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame0.setLineWidth(2)
        self.frame0.setObjectName("frame0")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_showtext = QtWidgets.QFrame(self.frame0)
        self.frame_showtext.setStyleSheet("background-color: rgb(122, 122, 122);")
        self.frame_showtext.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_showtext.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_showtext.setLineWidth(2)
        self.frame_showtext.setObjectName("frame_showtext")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_showtext)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_directory = QtWidgets.QLabel(self.frame_showtext)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_directory.setFont(font)
        self.label_directory.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"font: 75 14pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid  rgb(56, 56, 56);\n"
"border-radius: 5px\n"
"")
        self.label_directory.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_directory.setObjectName("label_directory")
        self.gridLayout_2.addWidget(self.label_directory, 0, 0, 1, 4)
        self.textBrowser_showfile = QtWidgets.QTextBrowser(self.frame_showtext)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_showfile.setFont(font)
        self.textBrowser_showfile.setStyleSheet("background-color: rgb(195, 195, 195);\n"
"border: 3px solid  rgb(56, 56, 56);\n"
"border-radius: 10px")
        self.textBrowser_showfile.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_showfile.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_showfile.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textBrowser_showfile.setReadOnly(False)
        self.textBrowser_showfile.setOverwriteMode(True)
        self.textBrowser_showfile.setObjectName("textBrowser_showfile")
        self.gridLayout_2.addWidget(self.textBrowser_showfile, 1, 0, 2, 4)
        self.pushButton_pause = QtWidgets.QPushButton(self.frame_showtext)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_pause.setFont(font)
        self.pushButton_pause.setMouseTracking(True)
        self.pushButton_pause.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_pause.setAutoFillBackground(False)
        self.pushButton_pause.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_pause.setFlat(False)
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.gridLayout_2.addWidget(self.pushButton_pause, 5, 0, 1, 1)
        self.label_showline = QtWidgets.QLabel(self.frame_showtext)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_showline.setFont(font)
        self.label_showline.setStyleSheet("background-color: rgb(195, 195, 195);\n"
"color: rgb(36, 36, 36);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"font: 75 18pt \"Arial\";\n"
"border: 3px solid  rgb(56, 56, 56);\n"
"border-radius: 5px;")
        self.label_showline.setObjectName("label_showline")
        self.gridLayout_2.addWidget(self.label_showline, 3, 0, 1, 4)
        self.pushButton_jog = QtWidgets.QPushButton(self.frame_showtext)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_jog.setFont(font)
        self.pushButton_jog.setMouseTracking(True)
        self.pushButton_jog.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_jog.setAutoFillBackground(False)
        self.pushButton_jog.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_jog.setFlat(False)
        self.pushButton_jog.setObjectName("pushButton_jog")
        self.gridLayout_2.addWidget(self.pushButton_jog, 5, 1, 1, 1)
        self.pushButton_auto = QtWidgets.QPushButton(self.frame_showtext)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_auto.setFont(font)
        self.pushButton_auto.setMouseTracking(True)
        self.pushButton_auto.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_auto.setAutoFillBackground(False)
        self.pushButton_auto.setStyleSheet("background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_auto.setFlat(False)
        self.pushButton_auto.setObjectName("pushButton_auto")
        self.gridLayout_2.addWidget(self.pushButton_auto, 5, 2, 1, 1)
        self.label_showtime = QtWidgets.QLabel(self.frame_showtext)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_showtime.setFont(font)
        self.label_showtime.setStyleSheet("background-color: rgb(195, 195, 195);\n"
"color: rgb(36, 36, 36);\n"
"border: 3px solid  rgb(56, 56, 56);\n"
"border-radius: 5px")
        self.label_showtime.setObjectName("label_showtime")
        self.gridLayout_2.addWidget(self.label_showtime, 5, 3, 1, 1)
        self.gridLayout_8.addWidget(self.frame_showtext, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame0)
        self.frame.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_y5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y5.setFont(font)
        self.label_y5.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y5.setObjectName("label_y5")
        self.gridLayout_7.addWidget(self.label_y5, 4, 4, 1, 1)
        self.label_x13 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x13.setFont(font)
        self.label_x13.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x13.setObjectName("label_x13")
        self.gridLayout_7.addWidget(self.label_x13, 4, 1, 1, 1)
        self.checkBoxY10 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY10.setTristate(False)
        self.checkBoxY10.setObjectName("checkBoxY10")
        self.gridLayout_7.addWidget(self.checkBoxY10, 1, 5, 1, 1)
        self.label_x5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x5.setFont(font)
        self.label_x5.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x5.setObjectName("label_x5")
        self.gridLayout_7.addWidget(self.label_x5, 4, 0, 1, 1)
        self.label_x11 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x11.setFont(font)
        self.label_x11.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x11.setObjectName("label_x11")
        self.gridLayout_7.addWidget(self.label_x11, 2, 1, 1, 1)
        self.label_y10 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y10.setFont(font)
        self.label_y10.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y10.setObjectName("label_y10")
        self.gridLayout_7.addWidget(self.label_y10, 1, 6, 1, 1)
        self.label_x3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x3.setFont(font)
        self.label_x3.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x3.setObjectName("label_x3")
        self.gridLayout_7.addWidget(self.label_x3, 2, 0, 1, 1)
        self.label_y15 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y15.setFont(font)
        self.label_y15.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y15.setObjectName("label_y15")
        self.gridLayout_7.addWidget(self.label_y15, 6, 6, 1, 1)
        self.label_y4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y4.setFont(font)
        self.label_y4.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y4.setObjectName("label_y4")
        self.gridLayout_7.addWidget(self.label_y4, 3, 4, 1, 1)
        self.label_y1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y1.setFont(font)
        self.label_y1.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y1.setLineWidth(1)
        self.label_y1.setMidLineWidth(0)
        self.label_y1.setObjectName("label_y1")
        self.gridLayout_7.addWidget(self.label_y1, 0, 4, 1, 1)
        self.label_x1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x1.setFont(font)
        self.label_x1.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x1.setObjectName("label_x1")
        self.gridLayout_7.addWidget(self.label_x1, 0, 0, 1, 1)
        self.label_x9 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x9.setFont(font)
        self.label_x9.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x9.setObjectName("label_x9")
        self.gridLayout_7.addWidget(self.label_x9, 0, 1, 1, 1)
        self.value_speedSpray = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_speedSpray.sizePolicy().hasHeightForWidth())
        self.value_speedSpray.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.value_speedSpray.setFont(font)
        self.value_speedSpray.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.value_speedSpray.setObjectName("value_speedSpray")
        self.gridLayout_7.addWidget(self.value_speedSpray, 0, 7, 1, 1)
        self.label_y9 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y9.setFont(font)
        self.label_y9.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y9.setObjectName("label_y9")
        self.gridLayout_7.addWidget(self.label_y9, 0, 6, 1, 1)
        self.checkBoxY9 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY9.setTristate(False)
        self.checkBoxY9.setObjectName("checkBoxY9")
        self.gridLayout_7.addWidget(self.checkBoxY9, 0, 5, 1, 1)
        self.label_x14 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x14.setFont(font)
        self.label_x14.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x14.setObjectName("label_x14")
        self.gridLayout_7.addWidget(self.label_x14, 5, 1, 1, 1)
        self.label_y13 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y13.setFont(font)
        self.label_y13.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y13.setObjectName("label_y13")
        self.gridLayout_7.addWidget(self.label_y13, 4, 6, 1, 1)
        self.label_y11 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y11.setFont(font)
        self.label_y11.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y11.setObjectName("label_y11")
        self.gridLayout_7.addWidget(self.label_y11, 2, 6, 1, 1)
        self.checkBoxY14 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY14.setTristate(False)
        self.checkBoxY14.setObjectName("checkBoxY14")
        self.gridLayout_7.addWidget(self.checkBoxY14, 5, 5, 1, 1)
        self.label_y6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y6.setFont(font)
        self.label_y6.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y6.setObjectName("label_y6")
        self.gridLayout_7.addWidget(self.label_y6, 5, 4, 1, 1)
        self.label_x6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x6.setFont(font)
        self.label_x6.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x6.setObjectName("label_x6")
        self.gridLayout_7.addWidget(self.label_x6, 5, 0, 1, 1)
        self.checkBoxY13 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY13.setTristate(False)
        self.checkBoxY13.setObjectName("checkBoxY13")
        self.gridLayout_7.addWidget(self.checkBoxY13, 4, 5, 1, 1)
        self.label_x10 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x10.setFont(font)
        self.label_x10.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x10.setObjectName("label_x10")
        self.gridLayout_7.addWidget(self.label_x10, 1, 1, 1, 1)
        self.label_y12 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y12.setFont(font)
        self.label_y12.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y12.setObjectName("label_y12")
        self.gridLayout_7.addWidget(self.label_y12, 3, 6, 1, 1)
        self.checkBoxY11 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY11.setTristate(False)
        self.checkBoxY11.setObjectName("checkBoxY11")
        self.gridLayout_7.addWidget(self.checkBoxY11, 2, 5, 1, 1)
        self.label_x4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x4.setFont(font)
        self.label_x4.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x4.setObjectName("label_x4")
        self.gridLayout_7.addWidget(self.label_x4, 3, 0, 1, 1)
        self.label_x2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x2.setFont(font)
        self.label_x2.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x2.setObjectName("label_x2")
        self.gridLayout_7.addWidget(self.label_x2, 1, 0, 1, 1)
        self.label_y2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y2.setFont(font)
        self.label_y2.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y2.setObjectName("label_y2")
        self.gridLayout_7.addWidget(self.label_y2, 1, 4, 1, 1)
        self.verticalSlider_speedMotor = QtWidgets.QSlider(self.frame)
        self.verticalSlider_speedMotor.setMinimum(10)
        self.verticalSlider_speedMotor.setMaximum(200)
        self.verticalSlider_speedMotor.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_speedMotor.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.verticalSlider_speedMotor.setTickInterval(1)
        self.verticalSlider_speedMotor.setObjectName("verticalSlider_speedMotor")
        self.gridLayout_7.addWidget(self.verticalSlider_speedMotor, 1, 8, 7, 1)
        self.checkBoxY12 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY12.setTristate(False)
        self.checkBoxY12.setObjectName("checkBoxY12")
        self.gridLayout_7.addWidget(self.checkBoxY12, 3, 5, 1, 1)
        self.label_x12 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x12.setFont(font)
        self.label_x12.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x12.setObjectName("label_x12")
        self.gridLayout_7.addWidget(self.label_x12, 3, 1, 1, 1)
        self.label_y3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y3.setFont(font)
        self.label_y3.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y3.setObjectName("label_y3")
        self.gridLayout_7.addWidget(self.label_y3, 2, 4, 1, 1)
        self.label_speedMotor = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_speedMotor.setFont(font)
        self.label_speedMotor.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_speedMotor.setObjectName("label_speedMotor")
        self.gridLayout_7.addWidget(self.label_speedMotor, 0, 8, 1, 1)
        self.label_x15 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x15.setFont(font)
        self.label_x15.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x15.setObjectName("label_x15")
        self.gridLayout_7.addWidget(self.label_x15, 6, 1, 1, 1)
        self.checkBoxY16 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY16.setTristate(False)
        self.checkBoxY16.setObjectName("checkBoxY16")
        self.gridLayout_7.addWidget(self.checkBoxY16, 7, 5, 1, 1)
        self.label_x8 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x8.setFont(font)
        self.label_x8.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x8.setObjectName("label_x8")
        self.gridLayout_7.addWidget(self.label_x8, 7, 0, 1, 1)
        self.label_x7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x7.setFont(font)
        self.label_x7.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x7.setObjectName("label_x7")
        self.gridLayout_7.addWidget(self.label_x7, 6, 0, 1, 1)
        self.label_y7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y7.setFont(font)
        self.label_y7.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y7.setObjectName("label_y7")
        self.gridLayout_7.addWidget(self.label_y7, 6, 4, 1, 1)
        self.label_x16 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_x16.setFont(font)
        self.label_x16.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_x16.setObjectName("label_x16")
        self.gridLayout_7.addWidget(self.label_x16, 7, 1, 1, 1)
        self.label_y16 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y16.setFont(font)
        self.label_y16.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y16.setObjectName("label_y16")
        self.gridLayout_7.addWidget(self.label_y16, 7, 6, 1, 1)
        self.label_y14 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y14.setFont(font)
        self.label_y14.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y14.setObjectName("label_y14")
        self.gridLayout_7.addWidget(self.label_y14, 5, 6, 1, 1)
        self.checkBoxY15 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY15.setTristate(False)
        self.checkBoxY15.setObjectName("checkBoxY15")
        self.gridLayout_7.addWidget(self.checkBoxY15, 6, 5, 1, 1)
        self.label_y8 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_y8.setFont(font)
        self.label_y8.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" bold;\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_y8.setObjectName("label_y8")
        self.gridLayout_7.addWidget(self.label_y8, 7, 4, 1, 1)
        self.checkBoxY4 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY4.setTristate(False)
        self.checkBoxY4.setObjectName("checkBoxY4")
        self.gridLayout_7.addWidget(self.checkBoxY4, 3, 2, 1, 1)
        self.checkBoxY1 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY1.setTristate(False)
        self.checkBoxY1.setObjectName("checkBoxY1")
        self.gridLayout_7.addWidget(self.checkBoxY1, 0, 2, 1, 1)
        self.verticalSlider_spray = QtWidgets.QSlider(self.frame)
        self.verticalSlider_spray.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_spray.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.verticalSlider_spray.setTickInterval(1)
        self.verticalSlider_spray.setObjectName("verticalSlider_spray")
        self.gridLayout_7.addWidget(self.verticalSlider_spray, 1, 7, 7, 1)
        self.checkBoxY2 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY2.setTristate(False)
        self.checkBoxY2.setObjectName("checkBoxY2")
        self.gridLayout_7.addWidget(self.checkBoxY2, 1, 2, 1, 1)
        self.checkBoxY7 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY7.setTristate(False)
        self.checkBoxY7.setObjectName("checkBoxY7")
        self.gridLayout_7.addWidget(self.checkBoxY7, 6, 2, 1, 1)
        self.checkBoxY5 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY5.setTristate(False)
        self.checkBoxY5.setObjectName("checkBoxY5")
        self.gridLayout_7.addWidget(self.checkBoxY5, 4, 2, 1, 1)
        self.checkBoxY6 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY6.setTristate(False)
        self.checkBoxY6.setObjectName("checkBoxY6")
        self.gridLayout_7.addWidget(self.checkBoxY6, 5, 2, 1, 1)
        self.checkBoxY3 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY3.setTristate(False)
        self.checkBoxY3.setObjectName("checkBoxY3")
        self.gridLayout_7.addWidget(self.checkBoxY3, 2, 2, 1, 1)
        self.checkBoxY8 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxY8.setTristate(False)
        self.checkBoxY8.setObjectName("checkBoxY8")
        self.gridLayout_7.addWidget(self.checkBoxY8, 7, 2, 1, 1)
        self.gridLayout_8.addWidget(self.frame, 0, 1, 1, 1)
        self.frame_button = QtWidgets.QFrame(self.frame0)
        self.frame_button.setStyleSheet("background-color: rgb(122, 122, 122);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.frame_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button.setObjectName("frame_button")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_button)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_xhome = QtWidgets.QLabel(self.frame_button)
        font = QtGui.QFont()
        font.setFamily("Arial bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_xhome.setFont(font)
        self.label_xhome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(255, 0, 0);\n"
"font: 75 14pt \"Arial\" \"bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 2px")
        self.label_xhome.setObjectName("label_xhome")
        self.gridLayout_5.addWidget(self.label_xhome, 0, 0, 1, 1)
        self.label_xlimit = QtWidgets.QLabel(self.frame_button)
        font = QtGui.QFont()
        font.setFamily("Arial bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_xlimit.setFont(font)
        self.label_xlimit.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(255, 0, 0);\n"
"font: 75 14pt \"Arial\" \"bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 2px")
        self.label_xlimit.setObjectName("label_xlimit")
        self.gridLayout_5.addWidget(self.label_xlimit, 0, 4, 1, 1)
        self.label_ahome = QtWidgets.QLabel(self.frame_button)
        font = QtGui.QFont()
        font.setFamily("Arial bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_ahome.setFont(font)
        self.label_ahome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(255, 0, 0);\n"
"font: 75 14pt \"Arial\" \"bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 2px")
        self.label_ahome.setObjectName("label_ahome")
        self.gridLayout_5.addWidget(self.label_ahome, 0, 3, 1, 1)
        self.label_yhome = QtWidgets.QLabel(self.frame_button)
        font = QtGui.QFont()
        font.setFamily("Arial bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_yhome.setFont(font)
        self.label_yhome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(255, 0, 0);\n"
"font: 75 14pt \"Arial\" \"bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 2px")
        self.label_yhome.setObjectName("label_yhome")
        self.gridLayout_5.addWidget(self.label_yhome, 0, 1, 1, 1)
        self.label_ylimit = QtWidgets.QLabel(self.frame_button)
        font = QtGui.QFont()
        font.setFamily("Arial bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_ylimit.setFont(font)
        self.label_ylimit.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(255, 0, 0);\n"
"font: 75 14pt \"Arial\" \"bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 2px")
        self.label_ylimit.setObjectName("label_ylimit")
        self.gridLayout_5.addWidget(self.label_ylimit, 0, 5, 1, 1)
        self.label_alimit = QtWidgets.QLabel(self.frame_button)
        font = QtGui.QFont()
        font.setFamily("Arial bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_alimit.setFont(font)
        self.label_alimit.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(255, 0, 0);\n"
"font: 75 14pt \"Arial\" \"bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 2px")
        self.label_alimit.setObjectName("label_alimit")
        self.gridLayout_5.addWidget(self.label_alimit, 0, 7, 1, 1)
        self.label_zhome = QtWidgets.QLabel(self.frame_button)
        font = QtGui.QFont()
        font.setFamily("Arial bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_zhome.setFont(font)
        self.label_zhome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(255, 0, 0);\n"
"font: 75 14pt \"Arial\" \"bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 2px")
        self.label_zhome.setObjectName("label_zhome")
        self.gridLayout_5.addWidget(self.label_zhome, 0, 2, 1, 1)
        self.label_zlimit = QtWidgets.QLabel(self.frame_button)
        font = QtGui.QFont()
        font.setFamily("Arial bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_zlimit.setFont(font)
        self.label_zlimit.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(255, 0, 0);\n"
"font: 75 14pt \"Arial\" \"bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 2px")
        self.label_zlimit.setObjectName("label_zlimit")
        self.gridLayout_5.addWidget(self.label_zlimit, 0, 6, 1, 1)
        self.gridLayout_8.addWidget(self.frame_button, 1, 0, 1, 1)
        self.frame_termial = QtWidgets.QFrame(self.frame0)
        self.frame_termial.setStyleSheet("background-color: rgb(122, 122, 122);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.frame_termial.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_termial.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_termial.setObjectName("frame_termial")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_termial)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_position = QtWidgets.QFrame(self.frame_termial)
        self.frame_position.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.frame_position.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_position.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_position.setObjectName("frame_position")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_position)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.frame_position)
        self.label.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 4)
        self.label_8 = QtWidgets.QLabel(self.frame_position)
        self.label_8.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_position)
        self.label_3.setMinimumSize(QtCore.QSize(122, 30))
        self.label_3.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_Xposition = QtWidgets.QLabel(self.frame_position)
        font = QtGui.QFont()
        font.setFamily("Arial Bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_Xposition.setFont(font)
        self.label_Xposition.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Xposition.setObjectName("label_Xposition")
        self.gridLayout_6.addWidget(self.label_Xposition, 2, 1, 2, 1)
        self.label_Yposition = QtWidgets.QLabel(self.frame_position)
        font = QtGui.QFont()
        font.setFamily("Arial Bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_Yposition.setFont(font)
        self.label_Yposition.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Yposition.setObjectName("label_Yposition")
        self.gridLayout_6.addWidget(self.label_Yposition, 4, 1, 1, 1)
        self.label_Zhome = QtWidgets.QLabel(self.frame_position)
        self.label_Zhome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Zhome.setObjectName("label_Zhome")
        self.gridLayout_6.addWidget(self.label_Zhome, 5, 2, 2, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_position)
        self.label_9.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 5, 3, 1, 1)
        self.label_Aposition = QtWidgets.QLabel(self.frame_position)
        font = QtGui.QFont()
        font.setFamily("Arial Bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_Aposition.setFont(font)
        self.label_Aposition.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Aposition.setObjectName("label_Aposition")
        self.gridLayout_6.addWidget(self.label_Aposition, 7, 1, 1, 1)
        self.label_Bposition = QtWidgets.QLabel(self.frame_position)
        self.label_Bposition.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Bposition.setObjectName("label_Bposition")
        self.gridLayout_6.addWidget(self.label_Bposition, 8, 1, 2, 1)
        self.label_Ahome = QtWidgets.QLabel(self.frame_position)
        self.label_Ahome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Ahome.setObjectName("label_Ahome")
        self.gridLayout_6.addWidget(self.label_Ahome, 7, 2, 1, 1)
        self.label_Bhome = QtWidgets.QLabel(self.frame_position)
        self.label_Bhome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Bhome.setObjectName("label_Bhome")
        self.gridLayout_6.addWidget(self.label_Bhome, 8, 2, 2, 1)
        self.label_xSpray = QtWidgets.QLabel(self.frame_position)
        self.label_xSpray.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_xSpray.setObjectName("label_xSpray")
        self.gridLayout_6.addWidget(self.label_xSpray, 3, 3, 2, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_position)
        self.label_5.setMinimumSize(QtCore.QSize(122, 30))
        self.label_5.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_position)
        self.label_6.setMinimumSize(QtCore.QSize(122, 37))
        self.label_6.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 8, 0, 2, 1)
        self.label_Yhome = QtWidgets.QLabel(self.frame_position)
        self.label_Yhome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Yhome.setObjectName("label_Yhome")
        self.gridLayout_6.addWidget(self.label_Yhome, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_position)
        self.label_2.setMinimumSize(QtCore.QSize(122, 37))
        self.label_2.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 2, 0, 2, 1)
        self.label_Zposition = QtWidgets.QLabel(self.frame_position)
        font = QtGui.QFont()
        font.setFamily("Arial Bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_Zposition.setFont(font)
        self.label_Zposition.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Zposition.setObjectName("label_Zposition")
        self.gridLayout_6.addWidget(self.label_Zposition, 5, 1, 2, 1)
        self.label_ySpray = QtWidgets.QLabel(self.frame_position)
        self.label_ySpray.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_ySpray.setObjectName("label_ySpray")
        self.gridLayout_6.addWidget(self.label_ySpray, 6, 3, 2, 1)
        self.label_Xhome = QtWidgets.QLabel(self.frame_position)
        self.label_Xhome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Xhome.setObjectName("label_Xhome")
        self.gridLayout_6.addWidget(self.label_Xhome, 2, 2, 2, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_position)
        self.label_4.setMinimumSize(QtCore.QSize(122, 37))
        self.label_4.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 5, 0, 2, 1)
        self.label_zSpray = QtWidgets.QLabel(self.frame_position)
        self.label_zSpray.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_zSpray.setObjectName("label_zSpray")
        self.gridLayout_6.addWidget(self.label_zSpray, 9, 3, 2, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_position)
        self.label_7.setMinimumSize(QtCore.QSize(122, 30))
        self.label_7.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 10, 0, 1, 1)
        self.label_Chome = QtWidgets.QLabel(self.frame_position)
        self.label_Chome.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Chome.setObjectName("label_Chome")
        self.gridLayout_6.addWidget(self.label_Chome, 10, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_position)
        self.label_10.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"font: 75 14pt \"Arial\" bold;\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 8, 3, 1, 1)
        self.label_Cposition = QtWidgets.QLabel(self.frame_position)
        font = QtGui.QFont()
        font.setFamily("Arial Bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_Cposition.setFont(font)
        self.label_Cposition.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\" \"Bold\";\n"
"border: 1px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_Cposition.setObjectName("label_Cposition")
        self.gridLayout_6.addWidget(self.label_Cposition, 10, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_position, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_termial)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_termial, 1, 1, 3, 1)
        self.textBrowser_terminal = QtWidgets.QTextBrowser(self.frame0)
        self.textBrowser_terminal.setStyleSheet("background-color:  rgb(77, 77, 77);\n"
"font: 75 14pt \"Arial\";\n"
"color: rgb(0, 250, 0);\n"
"border: 3px solid  rgb(56, 56, 56);\n"
"border-radius: 10px")
        self.textBrowser_terminal.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_terminal.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_terminal.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textBrowser_terminal.setReadOnly(True)
        self.textBrowser_terminal.setOverwriteMode(False)
        self.textBrowser_terminal.setObjectName("textBrowser_terminal")
        self.gridLayout_8.addWidget(self.textBrowser_terminal, 2, 0, 1, 1)
        self.frame_button_2 = QtWidgets.QFrame(self.frame0)
        self.frame_button_2.setStyleSheet("background-color: rgb(122, 122, 122);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.frame_button_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_2.setObjectName("frame_button_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_button_2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_power = QtWidgets.QPushButton(self.frame_button_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_power.setFont(font)
        self.pushButton_power.setMouseTracking(False)
        self.pushButton_power.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_power.setAutoFillBackground(False)
        self.pushButton_power.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.pushButton_power.setObjectName("pushButton_power")
        self.gridLayout.addWidget(self.pushButton_power, 0, 0, 1, 1)
        self.pushButton_estop = QtWidgets.QPushButton(self.frame_button_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_estop.setFont(font)
        self.pushButton_estop.setMouseTracking(True)
        self.pushButton_estop.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_estop.setAutoFillBackground(False)
        self.pushButton_estop.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-top-color: rgb(208, 208, 208);")
        self.pushButton_estop.setFlat(False)
        self.pushButton_estop.setObjectName("pushButton_estop")
        self.gridLayout.addWidget(self.pushButton_estop, 0, 1, 1, 1)
        self.pushButton_gotozero = QtWidgets.QPushButton(self.frame_button_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_gotozero.setFont(font)
        self.pushButton_gotozero.setMouseTracking(False)
        self.pushButton_gotozero.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_gotozero.setAutoFillBackground(False)
        self.pushButton_gotozero.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.pushButton_gotozero.setObjectName("pushButton_gotozero")
        self.gridLayout.addWidget(self.pushButton_gotozero, 0, 2, 1, 1)
        self.pushButton_machinehome = QtWidgets.QPushButton(self.frame_button_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_machinehome.sizePolicy().hasHeightForWidth())
        self.pushButton_machinehome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_machinehome.setFont(font)
        self.pushButton_machinehome.setMouseTracking(False)
        self.pushButton_machinehome.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_machinehome.setAutoFillBackground(False)
        self.pushButton_machinehome.setStyleSheet("background-color: rgb(173, 51, 10);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.pushButton_machinehome.setObjectName("pushButton_machinehome")
        self.gridLayout.addWidget(self.pushButton_machinehome, 0, 3, 1, 1)
        self.gridLayout_8.addWidget(self.frame_button_2, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame0, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1250, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuComunication = QtWidgets.QMenu(self.menubar)
        self.menuComunication.setObjectName("menuComunication")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuAbout_3 = QtWidgets.QMenu(self.menubar)
        self.menuAbout_3.setObjectName("menuAbout_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionChoose_File_pnt = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.actionChoose_File_pnt.setFont(font)
        self.actionChoose_File_pnt.setObjectName("actionChoose_File_pnt")
        self.actionSave_file = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionSave_file.setFont(font)
        self.actionSave_file.setObjectName("actionSave_file")
        self.actionMotor = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionMotor.setFont(font)
        self.actionMotor.setObjectName("actionMotor")
        self.actionTeach_mode = QtWidgets.QAction(MainWindow)
        self.actionTeach_mode.setObjectName("actionTeach_mode")
        self.actionAbout_Machine = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionAbout_Machine.setFont(font)
        self.actionAbout_Machine.setObjectName("actionAbout_Machine")
        self.actionContact = QtWidgets.QAction(MainWindow)
        self.actionContact.setObjectName("actionContact")
        self.actionConnect_to_Slave = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionConnect_to_Slave.setFont(font)
        self.actionConnect_to_Slave.setObjectName("actionConnect_to_Slave")
        self.actionAbout_Machine_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_Machine_2.setObjectName("actionAbout_Machine_2")
        self.actionContact_2 = QtWidgets.QAction(MainWindow)
        self.actionContact_2.setObjectName("actionContact_2")
        self.actionAbout_Machine_3 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionAbout_Machine_3.setFont(font)
        self.actionAbout_Machine_3.setObjectName("actionAbout_Machine_3")
        self.actionContact_3 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionContact_3.setFont(font)
        self.actionContact_3.setObjectName("actionContact_3")
        self.actionTeach_mode_2 = QtWidgets.QAction(MainWindow)
        self.actionTeach_mode_2.setObjectName("actionTeach_mode_2")
        self.actionTeach_mode_3 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionTeach_mode_3.setFont(font)
        self.actionTeach_mode_3.setObjectName("actionTeach_mode_3")
        self.actionDefine_XY = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.actionDefine_XY.setFont(font)
        self.actionDefine_XY.setObjectName("actionDefine_XY")
        self.actionSettings_Distance = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionSettings_Distance.setFont(font)
        self.actionSettings_Distance.setObjectName("actionSettings_Distance")
        self.menuFile.addAction(self.actionChoose_File_pnt)
        self.menuFile.addAction(self.actionSave_file)
        self.menuSetting.addAction(self.actionMotor)
        self.menuSetting.addAction(self.actionDefine_XY)
        self.menuSetting.addAction(self.actionSettings_Distance)
        self.menuComunication.addAction(self.actionConnect_to_Slave)
        self.menuAbout.addAction(self.actionAbout_Machine)
        self.menuAbout.addAction(self.actionTeach_mode_3)
        self.menuAbout_3.addAction(self.actionAbout_Machine_3)
        self.menuAbout_3.addAction(self.actionContact_3)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuComunication.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuAbout_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RoyalRobotics - Khoi Nguyen Plastic.jsc - Automatic Painting Machine"))
        self.label_directory.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">NO FILE LOADED</span></p></body></html>"))
        self.pushButton_pause.setText(_translate("MainWindow", "PAUSE"))
        self.label_showline.setText(_translate("MainWindow", "Show line"))
        self.pushButton_jog.setText(_translate("MainWindow", "JOG"))
        self.pushButton_auto.setText(_translate("MainWindow", "AUTO"))
        self.label_showtime.setText(_translate("MainWindow", "0:00:00"))
        self.label_y5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y5</span></p></body></html>"))
        self.label_x13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X13</span></p></body></html>"))
        self.checkBoxY10.setText(_translate("MainWindow", "CheckBoxY10"))
        self.label_x5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X5</span></p></body></html>"))
        self.label_x11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X11</span></p></body></html>"))
        self.label_y10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y10</span></p></body></html>"))
        self.label_x3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X3</span></p></body></html>"))
        self.label_y15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y15</span></p></body></html>"))
        self.label_y4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y4</span></p></body></html>"))
        self.label_y1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y1</span></p></body></html>"))
        self.label_x1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X1</span></p></body></html>"))
        self.label_x9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X9</span></p></body></html>"))
        self.value_speedSpray.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">0</span></p></body></html>"))
        self.label_y9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y9</span></p></body></html>"))
        self.checkBoxY9.setText(_translate("MainWindow", "CheckBoxY9"))
        self.label_x14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X14</span></p></body></html>"))
        self.label_y13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y13</span></p></body></html>"))
        self.label_y11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y11</span></p></body></html>"))
        self.checkBoxY14.setText(_translate("MainWindow", "CheckBoxY14"))
        self.label_y6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y6</span></p></body></html>"))
        self.label_x6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X6</span></p></body></html>"))
        self.checkBoxY13.setText(_translate("MainWindow", "CheckBoxY13"))
        self.label_x10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X10</span></p></body></html>"))
        self.label_y12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y12</span></p></body></html>"))
        self.checkBoxY11.setText(_translate("MainWindow", "CheckBoxY11"))
        self.label_x4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X4</span></p></body></html>"))
        self.label_x2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X2</span></p></body></html>"))
        self.label_y2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y2</span></p></body></html>"))
        self.checkBoxY12.setText(_translate("MainWindow", "CheckBoxY12"))
        self.label_x12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X12</span></p></body></html>"))
        self.label_y3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y3</span></p></body></html>"))
        self.label_speedMotor.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ff0000;\">0</span></p></body></html>"))
        self.label_x15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X15</span></p></body></html>"))
        self.checkBoxY16.setText(_translate("MainWindow", "CheckBoxY16"))
        self.label_x8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X8</span></p></body></html>"))
        self.label_x7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X7</span></p></body></html>"))
        self.label_y7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y7</span></p></body></html>"))
        self.label_x16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X16</span></p></body></html>"))
        self.label_y16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y16</span></p></body></html>"))
        self.label_y14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y14</span></p></body></html>"))
        self.checkBoxY15.setText(_translate("MainWindow", "CheckBoxY15"))
        self.label_y8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y8</span></p></body></html>"))
        self.checkBoxY4.setText(_translate("MainWindow", "CheckBoxY4"))
        self.checkBoxY1.setText(_translate("MainWindow", "CheckBoxY1"))
        self.checkBoxY2.setText(_translate("MainWindow", "CheckBoxY2"))
        self.checkBoxY7.setText(_translate("MainWindow", "CheckBoxY7"))
        self.checkBoxY5.setText(_translate("MainWindow", "CheckBoxY5"))
        self.checkBoxY6.setText(_translate("MainWindow", "CheckBoxY6"))
        self.checkBoxY3.setText(_translate("MainWindow", "CheckBoxY3"))
        self.checkBoxY8.setText(_translate("MainWindow", "CheckBoxY8"))
        self.label_xhome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">X-HOME</span></p></body></html>"))
        self.label_xlimit.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">X-LIMIT</span></p></body></html>"))
        self.label_ahome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">A-HOME</span></p></body></html>"))
        self.label_yhome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Y-HOME</span></p></body></html>"))
        self.label_ylimit.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Y-LIMIT</span></p></body></html>"))
        self.label_alimit.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">A-LIMIT</span></p></body></html>"))
        self.label_zhome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Z-HOME</span></p></body></html>"))
        self.label_zlimit.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Z-LIMIT</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">AXIS -- G54WORK --- MACHINE ---- GUN</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">X</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y</span></p></body></html>"))
        self.label_Xposition.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Yposition.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Zhome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Y</span></p></body></html>"))
        self.label_Aposition.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Bposition.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Ahome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Bhome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_xSpray.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">A</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">B</span></p></body></html>"))
        self.label_Yhome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X</span></p></body></html>"))
        self.label_Zposition.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_ySpray.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_Xhome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Z</span></p></body></html>"))
        self.label_zSpray.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">C</span></p></body></html>"))
        self.label_Chome.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Z</span></p></body></html>"))
        self.label_Cposition.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">0</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Design by: Khanh.Q.N - Khoi Nguyen Plastic.jsc - 0348777219"))
        self.pushButton_power.setText(_translate("MainWindow", "POWER"))
        self.pushButton_estop.setText(_translate("MainWindow", "E-STOP"))
        self.pushButton_gotozero.setText(_translate("MainWindow", "GO TO ZERO"))
        self.pushButton_machinehome.setText(_translate("MainWindow", "MACHINE HOME"))
        self.menuFile.setTitle(_translate("MainWindow", "FILE"))
        self.menuSetting.setTitle(_translate("MainWindow", "SETTINGS"))
        self.menuComunication.setTitle(_translate("MainWindow", "COMMUNICATION"))
        self.menuAbout.setTitle(_translate("MainWindow", "MANUAL"))
        self.menuAbout_3.setTitle(_translate("MainWindow", "ABOUT"))
        self.actionChoose_File_pnt.setText(_translate("MainWindow", "Choose file (.pnt)"))
        self.actionSave_file.setText(_translate("MainWindow", "Save file"))
        self.actionMotor.setText(_translate("MainWindow", "Motor"))
        self.actionTeach_mode.setText(_translate("MainWindow", "Teach mode"))
        self.actionAbout_Machine.setText(_translate("MainWindow", "Toggle coil Y"))
        self.actionContact.setText(_translate("MainWindow", "Contact"))
        self.actionConnect_to_Slave.setText(_translate("MainWindow", "Connect to Slave"))
        self.actionAbout_Machine_2.setText(_translate("MainWindow", "About Machine"))
        self.actionContact_2.setText(_translate("MainWindow", "Contact"))
        self.actionAbout_Machine_3.setText(_translate("MainWindow", "About Machine"))
        self.actionContact_3.setText(_translate("MainWindow", "Contact"))
        self.actionTeach_mode_2.setText(_translate("MainWindow", "Teach mode"))
        self.actionTeach_mode_3.setText(_translate("MainWindow", "Teach mode"))
        self.actionDefine_XY.setText(_translate("MainWindow", "Define XY"))
        self.actionSettings_Distance.setText(_translate("MainWindow", "Settings Distance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
